//! Flash and RAM layout for the scoreboard firmware.
//!
//! THE single source of truth: `app/build.rs` generates the binary's
//! `memory.x` from these constants, and Phase 4's OTA path reads the same
//! partition offsets at runtime, so the linker script and the code that writes
//! flash cannot disagree. SPEC §8's "encoded in `memory.x`, generated by
//! `build.rs` from one constants file" is this crate.
//!
//! The numbers are the ones the Phase 4 boot spike confirmed on hardware
//! (`firmware-rs/boot-spike/PARTITIONS.md`, verified 2026-08-07: swap,
//! trial-boot confirm, watchdog revert, mid-swap resume and ed25519 verify all
//! demonstrated on this exact table). `boot-spike/layout` is that spike's own
//! copy and keeps its bench-only extras — a demo command mailbox, pinned RTT
//! rings; this is the production copy and carries neither.
//!
//! | offset     | size            | region                                   |
//! |------------|-----------------|------------------------------------------|
//! | 0x00_0000  | 32 KB           | bootloader (bootrom reads its IMAGE_DEF) |
//! | 0x00_8000  | 8 KB            | embassy-boot state                       |
//! | 0x00_A000  | 1536 KB         | active image                             |
//! | 0x18_A000  | 1536 KB + 4 KB  | DFU (staging) image                      |
//! | 0x30_B000  | 980 KB          | storage (sequential-storage, SPEC §9)    |
//!
//! # Two link profiles, one table
//!
//! The same app binary links at one of two addresses:
//!
//! * [`Profile::Standalone`] — flash offset 0, no bootloader in the picture.
//!   Probe-flashed, `cargo run` works, nothing has to be staged or swapped.
//!   This is Phase 3's whole world.
//! * [`Profile::BootIntegrated`] — the active partition at `0x1000_A000`,
//!   behind embassy-boot, with the `__bootloader_*` symbols its
//!   `FirmwareUpdater` reads. Phase 4 flips to it.
//!
//! Both profiles stop short of [`STORAGE_OFFSET`], so the storage region sits
//! at the same address either way and the flip does not orphan saved config.

#![cfg_attr(not(feature = "std"), no_std)]

/// XIP window base: flash offset 0 appears at this bus address.
pub const FLASH_BASE: u32 = 0x1000_0000;
/// Pico 2 W: 4 MB QSPI flash.
pub const FLASH_SIZE: u32 = 4 * 1024 * 1024;
/// Smallest erasable unit; every partition boundary is a multiple.
pub const ERASE_SIZE: u32 = 4096;
/// `NorFlash::WRITE_SIZE` of embassy-rp's flash driver (it page-buffers
/// internally, so it can expose byte-granular writes). The state-partition
/// sizing rule below is stated in these units, and the rule flips hard if a
/// future embassy-rp raises this — hence the const assert.
pub const FLASH_WRITE_SIZE: u32 = 1;

/// Pico 2 W: 520 KB SRAM. The linker gets the 512 KB of contiguous striped
/// banks; the two 4 KB non-striped scratch banks stay out of the map, so
/// spending them takes a deliberate section placement (BUDGET.md).
pub const RAM_BASE: u32 = 0x2000_0000;
pub const RAM_SIZE: u32 = 512 * 1024;

/// RAM reserved at the very top for the crash breadcrumb cell
/// (`app/src/supervise.rs`), outside every binary's linker map.
///
/// The cell's whole job is to carry a record across a reset, and SRAM does
/// keep its contents — but drill day 2026-08-16 proved that surviving the
/// *reset* is not the property that matters: the **bootloader** runs between
/// the death and the next app boot, its stack starts at the top of *its* RAM
/// and grows down, and embassy-boot puts a 4 KB aligned page buffer on that
/// stack. A cell the app tucked into its own top-of-RAM `.uninit` was
/// observed intact one SWD sample after the panic and shredded by the next —
/// the promote-at-boot design had only ever been proven standalone, where
/// nothing runs in between.
///
/// So the cell gets an address no linker map contains: every profile's RAM
/// region now ends at [`BREADCRUMB_BASE`], which means no stack, no statics
/// and no startup code from either binary can reach it. The app reaches it
/// through this constant as a raw pointer — deliberately not a linker-placed
/// static, because a section in a region outside RAM trips over both
/// flip-link's inversion and cortex-m-rt's stack sanity assert, and a raw
/// pointer to a reserved address is the honest shape of the thing anyway.
/// `supervise.rs` const-asserts the cell type fits [`BREADCRUMB_SIZE`].
pub const BREADCRUMB_SIZE: u32 = 256;
pub const BREADCRUMB_BASE: u32 = RAM_BASE + RAM_SIZE - BREADCRUMB_SIZE;
/// What the linker may actually hand out: everything below the cell.
pub const LINKED_RAM_SIZE: u32 = RAM_SIZE - BREADCRUMB_SIZE;

/// Bootloader partition. Must start at flash offset 0: the RP2350 bootrom
/// scans the first 4 KB of flash for an IMAGE_DEF, and behind a bootloader
/// that image is the only one it ever sees.
pub const BOOT_OFFSET: u32 = 0;
pub const BOOT_SIZE: u32 = 32 * 1024;

/// embassy-boot state partition: magic byte + swap/revert progress arrays.
pub const STATE_OFFSET: u32 = BOOT_OFFSET + BOOT_SIZE;
pub const STATE_SIZE: u32 = 8 * 1024;

/// Active partition: the image the bootloader jumps into.
pub const ACTIVE_OFFSET: u32 = STATE_OFFSET + STATE_SIZE;
pub const ACTIVE_SIZE: u32 = 1536 * 1024;

/// DFU partition: OTA downloads land here and embassy-boot swaps it with
/// active. One erase page larger than active — the swap algorithm needs a
/// scratch page, and equal-size partitions panic the bootloader at its first
/// `prepare_boot()`.
pub const DFU_OFFSET: u32 = ACTIVE_OFFSET + ACTIVE_SIZE;
pub const DFU_SIZE: u32 = ACTIVE_SIZE + ERASE_SIZE;

/// Storage region (SPEC §9, sequential-storage): everything left over. Both
/// link profiles stop here, so config written under one survives the flip to
/// the other.
pub const STORAGE_OFFSET: u32 = DFU_OFFSET + DFU_SIZE;
pub const STORAGE_SIZE: u32 = FLASH_SIZE - STORAGE_OFFSET;

/// What [`Profile::Standalone`] gets: everything below the storage region.
/// Deliberately not "all of flash" — an app that grew into storage would
/// corrupt saved config the first time it linked, and silently.
pub const STANDALONE_SIZE: u32 = STORAGE_OFFSET;

const fn aligned(value: u32) -> bool {
    value.is_multiple_of(ERASE_SIZE)
}

// Partition arithmetic, checked at compile time. The last two restate
// `embassy_boot::BootLoader::assert_partitions`, so a layout the bootloader
// would panic on fails the build instead.
const _: () = {
    assert!(aligned(BOOT_OFFSET) && aligned(BOOT_SIZE));
    assert!(aligned(STATE_OFFSET) && aligned(STATE_SIZE));
    assert!(aligned(ACTIVE_OFFSET) && aligned(ACTIVE_SIZE));
    assert!(aligned(DFU_OFFSET) && aligned(DFU_SIZE));
    assert!(aligned(STORAGE_OFFSET) && aligned(STANDALONE_SIZE));
    assert!(STORAGE_OFFSET + STORAGE_SIZE == FLASH_SIZE);
    assert!(STORAGE_SIZE >= 512 * 1024);
    assert!(ACTIVE_SIZE <= STANDALONE_SIZE);
    assert!(DFU_SIZE >= ACTIVE_SIZE + ERASE_SIZE);
    assert!(2 + 4 * (ACTIVE_SIZE / ERASE_SIZE) <= STATE_SIZE / FLASH_WRITE_SIZE);
};

/// Which binary, and therefore which address, a `memory.x` is being generated
/// for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Profile {
    /// The app at flash offset 0, no bootloader. Phase 3, and still how the
    /// bench works — `cargo run` over the probe, nothing staged or swapped.
    Standalone,
    /// The app at the active partition, behind embassy-boot. Phase 4, and what
    /// `tools/build.py publish-fw` ships.
    BootIntegrated,
    /// `firmware-rs/boot` itself, at flash offset 0.
    ///
    /// It shares an origin with [`Profile::Standalone`] and nothing else: it is
    /// bounded by [`BOOT_SIZE`] rather than by the storage region, because
    /// everything above it belongs to a partition somebody else manages. An
    /// overlong bootloader would otherwise link straight over the state
    /// partition it is about to read.
    Bootloader,
}

impl Profile {
    /// `(origin, length)` of the FLASH region this profile links into.
    pub const fn flash_region(self) -> (u32, u32) {
        match self {
            Profile::Standalone => (FLASH_BASE + BOOT_OFFSET, STANDALONE_SIZE),
            Profile::BootIntegrated => (FLASH_BASE + ACTIVE_OFFSET, ACTIVE_SIZE),
            Profile::Bootloader => (FLASH_BASE + BOOT_OFFSET, BOOT_SIZE),
        }
    }

    /// Whether this binary reaches the partition table at runtime.
    ///
    /// The bootloader reads all three partitions; the boot-integrated app reads
    /// the state partition and writes DFU. [`Profile::Standalone`] has no
    /// bootloader in the picture at all, and a resolved `__bootloader_*` symbol
    /// there would be an invitation to write a partition nothing manages — so
    /// it deliberately gets a link error instead.
    pub const fn needs_partition_symbols(self) -> bool {
        matches!(self, Profile::BootIntegrated | Profile::Bootloader)
    }
}

/// Render the complete `memory.x` for one profile. Called from `build.rs`.
///
/// The block scaffolding is the RP2350 IMAGE_DEF plumbing every rp235x binary
/// needs: embassy-rp emits `.start_block`, the bootrom and `picotool` look for
/// it in the image's first 4 KB, and `.bi_entries`/`.end_block` let picotool
/// walk the metadata. Under [`Profile::BootIntegrated`] the app's own block is
/// inert at runtime — the bootloader reaches it by `VTOR` + `bootload`, never
/// through the bootrom — but it is kept so picotool still recognises the image.
#[cfg(feature = "std")]
pub fn memory_x(profile: Profile) -> String {
    let (origin, length) = profile.flash_region();
    // embassy-boot's `from_linkerfile_blocking()` hands these straight to
    // embassy-rp's Flash driver, which addresses flash from 0 — so they are
    // BYTE OFFSETS, not XIP addresses. The bootloader and the integrated app
    // both read them; see `Profile::needs_partition_symbols`.
    let bootloader_symbols = if !profile.needs_partition_symbols() {
        String::from(
            "/* Standalone profile: no bootloader, so no __bootloader_* symbols.\n\
             \x20  Building the OTA path against this profile is a link error, which is\n\
             \x20  the intended outcome. */\n",
        )
    } else {
        format!(
            "__bootloader_state_start = {STATE_OFFSET:#x};\n\
             __bootloader_state_end = {state_end:#x};\n\
             __bootloader_active_start = {ACTIVE_OFFSET:#x};\n\
             __bootloader_active_end = {active_end:#x};\n\
             __bootloader_dfu_start = {DFU_OFFSET:#x};\n\
             __bootloader_dfu_end = {dfu_end:#x};\n",
            state_end = STATE_OFFSET + STATE_SIZE,
            active_end = ACTIVE_OFFSET + ACTIVE_SIZE,
            dfu_end = DFU_OFFSET + DFU_SIZE,
        )
    };

    format!(
        r#"/* GENERATED by build.rs from scoreboard-layout — do not edit.
   Profile: {profile:?} */
MEMORY {{
    /* RAM stops one cell short of the silicon: the top BREADCRUMB_SIZE bytes
       are the crash record, reachable only through BREADCRUMB_BASE as a raw
       pointer — no linker map contains them, which is what protects the cell
       from the bootloader's top-of-RAM stack (the drill-day lesson). */
    FLASH : ORIGIN = {origin:#x}, LENGTH = {length:#x}
    RAM   : ORIGIN = {RAM_BASE:#x}, LENGTH = {LINKED_RAM_SIZE:#x}
}}

{bootloader_symbols}
SECTIONS {{
    /* Boot ROM IMAGE_DEF (emitted by embassy-rp), kept in the first 4 KB of
       the image, where the RP2350 boot ROM and picotool look for it. */
    .start_block : ALIGN(4)
    {{
        __start_block_addr = .;
        KEEP(*(.start_block));
        KEEP(*(.boot_info));
    }} > FLASH
}} INSERT AFTER .vector_table;

/* .text starts after the boot info */
_stext = ADDR(.start_block) + SIZEOF(.start_block);

SECTIONS {{
    /* picotool 'binary info' entries */
    .bi_entries : ALIGN(4)
    {{
        __bi_entries_start = .;
        KEEP(*(.bi_entries));
        . = ALIGN(4);
        __bi_entries_end = .;
    }} > FLASH
}} INSERT AFTER .text;

SECTIONS {{
    /* Trailing block pointing back at .start_block so picotool can walk
       the image metadata. */
    .end_block : ALIGN(4)
    {{
        __end_block_addr = .;
        KEEP(*(.end_block));
    }} > FLASH
}} INSERT AFTER .uninit;

PROVIDE(start_to_end = __end_block_addr - __start_block_addr);
PROVIDE(end_to_start = __start_block_addr - __end_block_addr);
"#
    )
}

#[cfg(all(test, feature = "std"))]
mod tests {
    use super::*;

    #[test]
    fn the_three_profiles_link_at_the_documented_addresses() {
        assert_eq!(
            Profile::Standalone.flash_region(),
            (0x1000_0000, 0x30_B000),
            "standalone links at the start of flash and stops below storage"
        );
        assert_eq!(
            Profile::BootIntegrated.flash_region(),
            (0x1000_A000, 0x18_0000),
            "integrated links at the active partition"
        );
        assert_eq!(
            Profile::Bootloader.flash_region(),
            (0x1000_0000, 0x00_8000),
            "the bootloader links at flash offset 0 and stops at the state partition"
        );
    }

    #[test]
    fn the_standalone_profile_alone_lacks_the_bootloader_symbols() {
        assert!(!memory_x(Profile::Standalone).contains("__bootloader_active_start"));
        assert!(memory_x(Profile::BootIntegrated).contains("__bootloader_active_start = 0xa000;"));
        // The bootloader reads all three partitions, so it needs them too —
        // `BootLoaderConfig::from_linkerfile_blocking` resolves exactly these.
        assert!(memory_x(Profile::Bootloader).contains("__bootloader_active_start = 0xa000;"));
        assert!(memory_x(Profile::Bootloader).contains("__bootloader_dfu_start = 0x18a000;"));
    }

    #[test]
    fn no_profile_can_reach_the_breadcrumb_cell() {
        // The property the panic record depends on: the cell's address is in
        // nobody's RAM region, so no stack — especially not the bootloader's,
        // which shredded it on drill day — and no startup code can touch it.
        assert_eq!(RAM_BASE + LINKED_RAM_SIZE, BREADCRUMB_BASE);
        assert_eq!(BREADCRUMB_BASE + BREADCRUMB_SIZE, RAM_BASE + RAM_SIZE);
        for profile in [
            Profile::Standalone,
            Profile::BootIntegrated,
            Profile::Bootloader,
        ] {
            let script = memory_x(profile);
            assert!(
                script.contains(&format!("RAM   : ORIGIN = 0x20000000, LENGTH = {LINKED_RAM_SIZE:#x}")),
                "{profile:?}'s RAM region must stop below the breadcrumb cell"
            );
        }
    }

    #[test]
    fn no_profile_reaches_into_storage() {
        for profile in [
            Profile::Standalone,
            Profile::BootIntegrated,
            Profile::Bootloader,
        ] {
            let (origin, length) = profile.flash_region();
            assert!(
                origin - FLASH_BASE + length <= STORAGE_OFFSET,
                "{profile:?} overlaps the storage region"
            );
        }
    }

    #[test]
    fn the_bootloader_cannot_link_over_the_state_partition() {
        // The failure this catches is silent and total: a bootloader that grew
        // past 32 KB would overwrite the swap-progress array it reads at every
        // boot, and would do so only for images past a size nobody is watching.
        let (origin, length) = Profile::Bootloader.flash_region();
        assert_eq!(origin - FLASH_BASE + length, STATE_OFFSET);
    }

    #[test]
    fn the_two_app_profiles_agree_about_where_storage_starts() {
        // The property that makes the standalone/boot-integrated flip safe: a
        // configuration written under one profile is read back under the other.
        // It holds because neither profile's region reaches STORAGE_OFFSET,
        // which the test above checks, and because `storage`'s region is
        // derived from these constants rather than from a literal.
        assert_eq!(STORAGE_OFFSET, DFU_OFFSET + DFU_SIZE);
        assert_eq!(STORAGE_OFFSET, 0x30_B000);
    }
}
