# Generated by tools/sprites/build.py from mlb_layout.png layer 'base_marker__relative'
# Mode: MONO_HLSB auto, 2 colors (transparent reserved), 3+4=7 bytes, 3x3
import framebuf

KEY = 0

WIDTH = 3
HEIGHT = 3

_data =\
b'\x40\xe0\x40'

_palette_data =\
b'\x1f\xf8\x42\xf7'

data = framebuf.FrameBuffer(bytearray(_data), WIDTH, HEIGHT, framebuf.MONO_HLSB)
palette = framebuf.FrameBuffer(bytearray(_palette_data), 2, 1, framebuf.RGB565)
