# Generated by tools/sprites/build.py from mlb_layout.png layer 'dot__relative'
# Mode: GS2_HMSB auto, 3 colors (transparent reserved), 4+6=10 bytes, 4x4
import framebuf

KEY = 0

WIDTH = 4
HEIGHT = 4

_data =\
b'\x14\x69\x69\x14'

_palette_data =\
b'\x1f\xf8\xff\xff\xaa\x52'

data = framebuf.FrameBuffer(bytearray(_data), WIDTH, HEIGHT, framebuf.GS2_HMSB)
palette = framebuf.FrameBuffer(bytearray(_palette_data), 3, 1, framebuf.RGB565)
