# Generated by tools/sprites/build.py from mlb_layout.png layer 'inning_bottom__absolute'
# Mode: MONO_HLSB auto, 2 colors (transparent reserved), 3+4=7 bytes, 5x3
import framebuf

KEY = 0
X = 9
Y = 33

WIDTH = 5
HEIGHT = 3

_data =\
b'\xf8\x70\x20'

_palette_data =\
b'\x1f\xf8\xff\xff'

data = framebuf.FrameBuffer(bytearray(_data), WIDTH, HEIGHT, framebuf.MONO_HLSB)
palette = framebuf.FrameBuffer(bytearray(_palette_data), 2, 1, framebuf.RGB565)
