"""
Simple font rendering for Hub75 displays.

Font modules are generated by tools/compile_fonts.py: each exposes `HEIGHT`,
a `GLYPHS` table indexed by `codepoint - 32` whose entries are ready-to-blit
`(memoryview, width, HEIGHT, framebuf.MONO_HLSB)` tuples, and a `DEFAULT`
fallback glyph. The tables are built once at import on Core 0, so every
render method here is allocation-free — safe to call from the Core 1 display
thread at frame rate.

Usage:
    from scoreboard.fonts import FontWriter, unscii_8, unscii_16

    writer = FontWriter(display.frame_buffer, default_font=unscii_8)
    writer.text("SCORE", 0, 0, color=0xFFFF)
    writer.text("24", 50, 0, color=0xF800, font=unscii_16)
"""
import framebuf
import micropython

# Alignment constants (integers to avoid allocations)
ALIGN_LEFT: int = 0
ALIGN_CENTER: int = 1
ALIGN_RIGHT: int = 2

# Transparency sentinel. Matches the _TRANSPARENT_RGB565 used by
# tools/compile_layout.py (this module is the single firmware definition).
# Used as the blit key when draw() is called with bgcolor=None.
MAGENTA_RGB565: int = 0xF81F

# Digit '0' and ':' positions in the GLYPHS table (codepoint - 32).
_DIGIT_BASE: int = ord('0') - 32  # 16
_COLON: int = ord(':') - 32       # 26


def _glyph(font, cp: int) -> tuple:
    """The single glyph-lookup path: table entry for a codepoint, DEFAULT
    ('?') for anything outside printable ASCII. Returns an existing tuple —
    never allocates."""
    i = cp - 32
    return font.GLYPHS[i] if 0 <= i < 95 else font.DEFAULT


def measure_text(string: str, font) -> int:
    """Measure text width in pixels for a font module."""
    width = 0
    for char in string:
        width += _glyph(font, ord(char))[1]
    return width


def calculate_scroll_offset(
    text_width: int,
    display_width: int,
    elapsed_ms: int,
    pause_ms: int = 2000,
    pixels_per_second: int = 30
) -> int:
    """
    Pure function: Given dimensions and elapsed time, return pixel offset.

    The animation cycle is:
        [pause_start] -> [scrolling] -> [pause_end] -> repeat
    """
    max_scroll = text_width - display_width
    if max_scroll <= 0:
        return 0

    scroll_duration_ms = (max_scroll * 1000) // pixels_per_second
    total_cycle_ms = pause_ms + scroll_duration_ms + pause_ms

    position = elapsed_ms % total_cycle_ms

    if position < pause_ms:
        # Phase 1: Paused at start
        return 0
    elif position < pause_ms + scroll_duration_ms:
        # Phase 2: Scrolling
        scroll_position = position - pause_ms
        return (scroll_position * pixels_per_second) // 1000
    else:
        # Phase 3: Paused at end
        return max_scroll


@micropython.viper
def rgb565(r: int, g: int, b: int) -> int:
    """Convert RGB888 to RGB565 color value."""
    return int(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))


class FontWriter:
    """
    Renders text using generated glyph-table fonts.

    Glyph entries blit directly (framebuf.blit accepts the table's
    (buffer, width, height, format) tuples); the only mutable state is the
    reusable 2-entry color palette. All render methods are allocation-free.
    """

    def __init__(self, framebuffer: framebuf.FrameBuffer, default_font=None):
        """
        Args:
            framebuffer: The RGB565 framebuffer to draw on
            default_font: Font module to use when none specified
        """
        self._fb: framebuf.FrameBuffer = framebuffer
        self._default_font = default_font

        # Reusable palette buffer (2 RGB565 entries = 4 bytes)
        # Index 0 = background color, Index 1 = foreground color
        self._palette_buf: bytearray = bytearray(4)
        self._palette: framebuf.FrameBuffer = framebuf.FrameBuffer(
            self._palette_buf, 2, 1, framebuf.RGB565
        )

        # Pre-allocated scratch space for integer() digit extraction
        # Avoids allocation during rendering - max 5 digits for scores
        self._int_digits: list = [0, 0, 0, 0, 0]

    def clock(self, seconds: int, x: int, y: int, width: int, align: int,
              color: int, bgcolor: int = 0, font=None) -> int:
        """
        Render [M]M:SS from seconds with zero allocations.

        Reserved for the future clock display (NBA); currently uncalled.

        Args:
            seconds: Total seconds (e.g., 225 for "3:45")
            x: Left edge of bounding box (pixels)
            y: Y position (pixels)
            width: Width of bounding box (pixels)
            align: ALIGN_LEFT, ALIGN_CENTER, or ALIGN_RIGHT
            color: Foreground color (RGB565)
            bgcolor: Background color (RGB565), default black
            font: Font module, or None to use default

        Returns:
            X position after last digit
        """
        if font is None:
            font = self._default_font
        glyphs = font.GLYPHS

        # Calculate minutes and seconds (pure integer math)
        if seconds < 0:
            seconds = 0
        minutes = seconds // 60
        secs = seconds % 60

        # Set up palette
        self._palette.pixel(0, 0, bgcolor)
        self._palette.pixel(1, 0, color)

        # Calculate total width for alignment
        total_width = 0
        if minutes >= 10:
            total_width += glyphs[_DIGIT_BASE + minutes // 10][1]
        total_width += glyphs[_DIGIT_BASE + minutes % 10][1]
        total_width += glyphs[_COLON][1]
        total_width += glyphs[_DIGIT_BASE + secs // 10][1]
        total_width += glyphs[_DIGIT_BASE + secs % 10][1]

        if align == ALIGN_CENTER:
            cursor_x = x + (width - total_width) // 2
        elif align == ALIGN_RIGHT:
            cursor_x = x + width - total_width
        else:  # ALIGN_LEFT
            cursor_x = x

        if minutes >= 10:
            g = glyphs[_DIGIT_BASE + minutes // 10]
            self._fb.blit(g, cursor_x, y, -1, self._palette)
            cursor_x += g[1]

        g = glyphs[_DIGIT_BASE + minutes % 10]
        self._fb.blit(g, cursor_x, y, -1, self._palette)
        cursor_x += g[1]

        g = glyphs[_COLON]
        self._fb.blit(g, cursor_x, y, -1, self._palette)
        cursor_x += g[1]

        g = glyphs[_DIGIT_BASE + secs // 10]
        self._fb.blit(g, cursor_x, y, -1, self._palette)
        cursor_x += g[1]

        g = glyphs[_DIGIT_BASE + secs % 10]
        self._fb.blit(g, cursor_x, y, -1, self._palette)
        cursor_x += g[1]

        return cursor_x

    def integer(self, value: int, x: int, y: int, width: int, align: int,
                color: int, bgcolor: int = 0, font=None) -> int:
        """
        Render an integer (0-99999) with zero allocations — exists so score
        rendering never builds a `str(value)`.

        Args:
            value: Integer to render (0-99999)
            x: Left edge of bounding box (pixels)
            y: Y position (pixels)
            width: Width of bounding box (pixels)
            align: ALIGN_LEFT, ALIGN_CENTER, or ALIGN_RIGHT
            color: Foreground color (RGB565)
            bgcolor: Background color (RGB565), default black
            font: Font module, or None to use default

        Returns:
            X position after last digit
        """
        if font is None:
            font = self._default_font
        glyphs = font.GLYPHS

        if value < 0:
            value = 0

        # Set up palette
        self._palette.pixel(0, 0, bgcolor)
        self._palette.pixel(1, 0, color)

        # Extract digits (reverse order) into pre-allocated scratch
        digits = self._int_digits
        num_digits = 0
        temp = value

        if temp == 0:
            digits[0] = 0
            num_digits = 1
        else:
            while temp > 0 and num_digits < 5:
                digits[num_digits] = temp % 10
                temp //= 10
                num_digits += 1

        # Calculate total width for alignment
        total_width = 0
        for i in range(num_digits):
            total_width += glyphs[_DIGIT_BASE + digits[i]][1]

        if align == ALIGN_CENTER:
            cursor_x = x + (width - total_width) // 2
        elif align == ALIGN_RIGHT:
            cursor_x = x + width - total_width
        else:  # ALIGN_LEFT
            cursor_x = x

        # Render digits (in reverse order since we extracted backwards)
        for i in range(num_digits - 1, -1, -1):
            g = glyphs[_DIGIT_BASE + digits[i]]
            self._fb.blit(g, cursor_x, y, -1, self._palette)
            cursor_x += g[1]

        return cursor_x

    def text(self, string: str, x: int, y: int, color: int,
             bgcolor: int = 0, font=None) -> int:
        """
        Draw text at position with specified color.

        Args:
            string: Text to render
            x: X position (pixels)
            y: Y position (pixels)
            color: Foreground color (RGB565)
            bgcolor: Background color (RGB565), default black
            font: Font module, or None to use default

        Returns:
            X position after last character (for chaining)
        """
        if font is None:
            font = self._default_font
        if font is None:
            raise ValueError("No font specified and no default set")

        # Set up palette: index 0 = bg, index 1 = fg
        self._palette.pixel(0, 0, bgcolor)
        self._palette.pixel(1, 0, color)

        cursor_x = x
        for char in string:
            g = _glyph(font, ord(char))
            self._fb.blit(g, cursor_x, y, -1, self._palette)
            cursor_x += g[1]

        return cursor_x

    def aligned_text(self, string: str, x: int, y: int, width: int, align: int,
                     color: int, bgcolor: int = 0, font=None) -> int:
        """
        Draw text aligned within a bounding box.

        Args:
            string: Text to render
            x: Left edge of bounding box (pixels)
            y: Y position (pixels)
            width: Width of bounding box (pixels)
            align: ALIGN_LEFT, ALIGN_CENTER, or ALIGN_RIGHT
            color: Foreground color (RGB565)
            bgcolor: Background color (RGB565), default black
            font: Font module, or None to use default

        Returns:
            X position after last character
        """
        if font is None:
            font = self._default_font
        if font is None:
            raise ValueError("No font specified and no default set")

        text_width = self.measure(string, font)

        if align == ALIGN_CENTER:
            start_x = x + (width - text_width) // 2
        elif align == ALIGN_RIGHT:
            start_x = x + width - text_width
        else:  # ALIGN_LEFT or default
            start_x = x

        return self.text(string, start_x, y, color, bgcolor, font)

    def draw(
        self,
        region,
        text: str,
        font,
        align: int,
        elapsed_ms: int,
        color: int,
        bgcolor=None,
        pause_ms: int = 2000,
        pixels_per_second: int = 30,
    ) -> None:
        """
        Draw text into a Region, auto-scrolling on overflow.

        Glyph blits are clipped to the region's bounds automatically — no
        manual fill_rect masking required. Scrolling activates when the
        measured text is wider than the region. Defaults to 30 px/sec with
        2000 ms dwell at each end, matching the pitcher/batter feel; callers
        can override either via `pause_ms` / `pixels_per_second`.

        Args:
            region: Region (or any framebuffer-like object exposing `.width`
                and supporting fill()/blit()). Sizes and stride are opaque.
            text: String to render.
            font: Font module (unscii_8, unscii_16, spleen_5x8). None = default.
            align: ALIGN_LEFT | ALIGN_CENTER | ALIGN_RIGHT. Ignored while scrolling.
            elapsed_ms: Milliseconds since animation_start_ms. Only consulted
                when text overflows and scrolling activates.
            color: Foreground color (RGB565).
            bgcolor: Optional background color (RGB565). If omitted, non-glyph
                pixels in the region are left untouched (transparent via the
                MAGENTA_RGB565 blit key).
            pause_ms: Dwell at each end of the scroll cycle (overflow only).
            pixels_per_second: Scroll speed (overflow only).
        """
        if font is None:
            font = self._default_font
        if font is None:
            raise ValueError("No font specified and no default set")

        width = region.width

        if bgcolor is not None:
            region.fill(bgcolor)
            self._palette.pixel(0, 0, bgcolor)
            key = -1
        else:
            self._palette.pixel(0, 0, MAGENTA_RGB565)
            key = MAGENTA_RGB565
        self._palette.pixel(1, 0, color)

        text_w = self.measure(text, font)

        if text_w <= width:
            if align == ALIGN_CENTER:
                cursor_x = (width - text_w) // 2
            elif align == ALIGN_RIGHT:
                cursor_x = width - text_w
            else:
                cursor_x = 0
        else:
            cursor_x = -calculate_scroll_offset(
                text_w, width, elapsed_ms,
                pause_ms=pause_ms, pixels_per_second=pixels_per_second,
            )

        for char in text:
            g = _glyph(font, ord(char))
            region.blit(g, cursor_x, 0, key, self._palette)
            cursor_x += g[1]

    def measure(self, string: str, font=None) -> int:
        """Measure text width in pixels."""
        if font is None:
            font = self._default_font
        if font is None:
            raise ValueError("No font specified and no default set")
        return measure_text(string, font)


# Import font modules for convenience
from . import unscii_8
from . import unscii_16
from . import spleen_5x8
