//! Flash partition layout for the embassy-boot A/B spike.
//!
//! THE single source of truth: the bootloader and app binaries generate their
//! `memory.x` from these constants in their build scripts, and the demo
//! tooling reads them too, so the three can't disagree. Phase 4 lifts this
//! crate (SPEC.md §8: "Encoded in `memory.x`, generated by `build.rs` from
//! one constants file").
//!
//! Layout on the Pico 2 W's 4 MB QSPI flash, all offsets relative to the
//! start of flash (XIP base 0x1000_0000):
//!
//! | offset     | size            | region                                   |
//! |------------|-----------------|------------------------------------------|
//! | 0x00_0000  | 32 KB           | bootloader (bootrom reads its IMAGE_DEF) |
//! | 0x00_8000  | 8 KB            | embassy-boot state                       |
//! | 0x00_A000  | 1536 KB         | active image                             |
//! | 0x18_A000  | 1536 KB + 4 KB  | DFU (staging) image                      |
//! | 0x30_B000  | 980 KB          | storage (sequential-storage, SPEC.md §9) |
//!
//! Deviations from the SPEC.md §8 draft ("boot 32 KB · state 8 KB · active
//! 1.5 MB · DFU 1.5 MB"), both forced by `embassy_boot`'s
//! `assert_partitions` (embassy-boot-0.7.0/src/boot_loader.rs):
//!
//! 1. **DFU must be at least one erase page (4 KB) bigger than active** —
//!    the swap algorithm needs a scratch page. "active 1.5 MB · DFU 1.5 MB"
//!    panics the bootloader at boot. DFU is therefore `ACTIVE + 4 KB`.
//! 2. The state partition must hold `2 + 4 × (active / 4096)` write-words.
//!    embassy-rp's flash driver exposes `WRITE_SIZE = 1`, so a 1536 KB
//!    active needs 1538 *bytes* of state — one 4 KB sector would do; the
//!    spec's 8 KB stands (margin, and room if a future embassy-rp raises
//!    WRITE_SIZE).
//!
//! The compile-time asserts at the bottom re-check all of this on every
//! build.

#![cfg_attr(not(feature = "std"), no_std)]

/// XIP window base: flash offset 0 appears at this bus address.
pub const FLASH_BASE: u32 = 0x1000_0000;
/// Pico 2 W: 4 MB QSPI flash.
pub const FLASH_SIZE: u32 = 4 * 1024 * 1024;
/// Smallest erasable unit; every partition boundary must be a multiple.
pub const ERASE_SIZE: u32 = 4096;
/// `NorFlash::WRITE_SIZE` of embassy-rp's flash driver (the driver
/// page-buffers internally, so it can expose byte-granular writes).
pub const FLASH_WRITE_SIZE: u32 = 1;

/// Pico 2 W: 520 KB SRAM; we expose the 512 KB striped main banks and leave
/// the two 4 KB scratch banks out, like the rest of firmware-rs.
pub const RAM_BASE: u32 = 0x2000_0000;
pub const RAM_SIZE: u32 = 512 * 1024;

/// Spike-only observation plumbing: each binary's defmt-rtt ring buffer is
/// pinned to its own well-known region at the top of RAM (the buffer lives
/// in `.uninit.defmt-rtt.BUFFER`, which is NOLOAD, so it relocates freely).
/// The demo's poller (demo/rtt_poll.py) reads both regions over SWD and can
/// attribute every frame to bootloader vs app without racing probe-rs's own
/// RTT session — probe-rs 0.32 prints nothing when stdout is not a terminal,
/// so `probe-rs run`-style streaming is useless for scripted capture.
/// Production keeps the default placement; none of this is part of the
/// Phase 4 layout.
pub const RTT_BUF_SIZE: u32 = 4096;
pub const RTT_BOOT_BUF: u32 = RAM_BASE + RAM_USABLE;
pub const RTT_APP_BUF: u32 = RTT_BOOT_BUF + RTT_BUF_SIZE;
/// RAM the binaries may use once the two RTT regions are carved off.
pub const RAM_USABLE: u32 = RAM_SIZE - 2 * RTT_BUF_SIZE;

/// Bootloader partition. Must start at flash offset 0: the RP2350 bootrom
/// scans the first 4 KB of flash for an IMAGE_DEF block, and the bootloader
/// is the only image the bootrom ever sees.
pub const BOOT_OFFSET: u32 = 0;
pub const BOOT_SIZE: u32 = 32 * 1024;

/// embassy-boot state partition: magic byte + swap/revert progress arrays.
pub const STATE_OFFSET: u32 = BOOT_OFFSET + BOOT_SIZE;
pub const STATE_SIZE: u32 = 8 * 1024;

/// Active partition: the image the bootloader jumps into. Apps link here.
pub const ACTIVE_OFFSET: u32 = STATE_OFFSET + STATE_SIZE;
pub const ACTIVE_SIZE: u32 = 1536 * 1024;

/// DFU partition: OTA downloads land here; embassy-boot swaps it with active.
/// One erase page larger than active — swap-algorithm scratch page.
pub const DFU_OFFSET: u32 = ACTIVE_OFFSET + ACTIVE_SIZE;
pub const DFU_SIZE: u32 = ACTIVE_SIZE + ERASE_SIZE;

/// Storage region (SPEC.md §9, sequential-storage): everything that's left.
pub const STORAGE_OFFSET: u32 = DFU_OFFSET + DFU_SIZE;
pub const STORAGE_SIZE: u32 = FLASH_SIZE - STORAGE_OFFSET;

/// Bench-only command mailbox for the spike demo: the host (probe-rs) writes
/// one byte into the first storage sector and resets the target; the app
/// reads and erases it at boot. Not part of the production layout.
pub const CMD_OFFSET: u32 = STORAGE_OFFSET;
/// Stage the embedded payload with plain `mark_updated` (non-verify builds).
pub const CMD_STAGE: u8 = 0x01;
/// Stage with `verify_and_mark_updated` and the embedded signature.
pub const CMD_STAGE_VERIFIED: u8 = 0x02;
/// Same, but corrupt the signature first — must be rejected.
pub const CMD_STAGE_BAD_SIG: u8 = 0x03;

const fn aligned(v: u32) -> bool {
    v % ERASE_SIZE == 0
}

// Partition arithmetic, checked at compile time. The last assert is
// embassy_boot::BootLoader's own `assert_partitions` restated, so a layout
// the bootloader would panic on fails the build instead.
const _: () = {
    assert!(aligned(BOOT_OFFSET) && aligned(BOOT_SIZE));
    assert!(aligned(STATE_OFFSET) && aligned(STATE_SIZE));
    assert!(aligned(ACTIVE_OFFSET) && aligned(ACTIVE_SIZE));
    assert!(aligned(DFU_OFFSET) && aligned(DFU_SIZE));
    assert!(aligned(STORAGE_OFFSET));
    assert!(STORAGE_OFFSET + STORAGE_SIZE == FLASH_SIZE);
    assert!(STORAGE_SIZE >= 512 * 1024); // §9 wants a real storage region left over
    assert!(DFU_SIZE >= ACTIVE_SIZE + ERASE_SIZE);
    assert!(2 + 4 * (ACTIVE_SIZE / ERASE_SIZE) <= STATE_SIZE / FLASH_WRITE_SIZE);
};

/// Which binary a `memory.x` is being generated for.
#[cfg(feature = "std")]
pub enum Region {
    /// Links at flash offset 0; sees the whole partition table.
    Bootloader,
    /// Links at the active partition.
    Application,
}

/// Render the complete `memory.x` for one of the two binaries. Called from
/// the binaries' build scripts; the block/section scaffolding is the RP2350
/// IMAGE_DEF plumbing every rp235x binary needs (same as hub75-diag's).
#[cfg(feature = "std")]
pub fn memory_x(region: Region) -> String {
    let (origin, length, rtt_buf) = match region {
        Region::Bootloader => (FLASH_BASE + BOOT_OFFSET, BOOT_SIZE, RTT_BOOT_BUF),
        Region::Application => (FLASH_BASE + ACTIVE_OFFSET, ACTIVE_SIZE, RTT_APP_BUF),
    };
    format!(
        r#"/* GENERATED by build.rs from spike-layout — do not edit. */
MEMORY {{
    FLASH : ORIGIN = {origin:#x}, LENGTH = {length:#x}
    RAM   : ORIGIN = {RAM_BASE:#x}, LENGTH = {RAM_USABLE:#x}
    RTT   : ORIGIN = {rtt_buf:#x}, LENGTH = {RTT_BUF_SIZE:#x}
}}

/* Pin this binary's defmt-rtt ring buffer to its dedicated region so the
   demo's SWD poller can tell bootloader frames from app frames. NOLOAD:
   the buffer is .uninit, nothing initializes it. Claimed here, before
   link.x's .uninit rule can. */
SECTIONS {{
    .defmt_rtt_buffer (NOLOAD) : ALIGN(4)
    {{
        KEEP(*(.uninit.defmt-rtt.BUFFER));
    }} > RTT
}} INSERT BEFORE .uninit;

/* embassy-boot partition symbols: BYTE OFFSETS FROM FLASH START, not XIP
   addresses — from_linkerfile_blocking() hands them straight to embassy-rp's
   Flash driver, which addresses flash from 0. */
__bootloader_state_start = {STATE_OFFSET:#x};
__bootloader_state_end = {state_end:#x};
__bootloader_active_start = {ACTIVE_OFFSET:#x};
__bootloader_active_end = {active_end:#x};
__bootloader_dfu_start = {DFU_OFFSET:#x};
__bootloader_dfu_end = {dfu_end:#x};

SECTIONS {{
    /* Boot ROM IMAGE_DEF (emitted by embassy-rp), kept in the first 4 KB of
       the image, where the RP2350 boot ROM and picotool look for it. */
    .start_block : ALIGN(4)
    {{
        __start_block_addr = .;
        KEEP(*(.start_block));
        KEEP(*(.boot_info));
    }} > FLASH
}} INSERT AFTER .vector_table;

/* .text starts after the boot info */
_stext = ADDR(.start_block) + SIZEOF(.start_block);

SECTIONS {{
    /* picotool 'binary info' entries */
    .bi_entries : ALIGN(4)
    {{
        __bi_entries_start = .;
        KEEP(*(.bi_entries));
        . = ALIGN(4);
        __bi_entries_end = .;
    }} > FLASH
}} INSERT AFTER .text;

SECTIONS {{
    /* Trailing block pointing back at .start_block so picotool can walk
       the image metadata. */
    .end_block : ALIGN(4)
    {{
        __end_block_addr = .;
        KEEP(*(.end_block));
    }} > FLASH
}} INSERT AFTER .uninit;

PROVIDE(start_to_end = __end_block_addr - __start_block_addr);
PROVIDE(end_to_start = __start_block_addr - __end_block_addr);
"#,
        state_end = STATE_OFFSET + STATE_SIZE,
        active_end = ACTIVE_OFFSET + ACTIVE_SIZE,
        dfu_end = DFU_OFFSET + DFU_SIZE,
    )
}
