//! Gamma LUTs vs the real driver.py's `_create_gamma_lut` output
//! (tests/goldens/mod.rs, generated by tests/gen_goldens.py).

#[path = "goldens/mod.rs"]
mod goldens;

use hub75::gamma::Gamma;

#[test]
fn srgb_matches_python() {
    assert_eq!(Gamma::Srgb.build_lut(), goldens::GAMMA_SRGB);
}

#[test]
fn power_curves_match_python() {
    assert_eq!(Gamma::Power(2.2).build_lut(), goldens::GAMMA_POWER_2_2);
    assert_eq!(Gamma::Power(2.4).build_lut(), goldens::GAMMA_POWER_2_4);
    assert_eq!(Gamma::Power(0.5).build_lut(), goldens::GAMMA_POWER_0_5);
}

#[test]
fn identity_matches_python() {
    assert_eq!(Gamma::Identity.build_lut(), goldens::GAMMA_IDENTITY);
}

#[test]
fn power_one_short_circuits_to_identity() {
    assert_eq!(Gamma::Power(1.0).build_lut(), goldens::GAMMA_POWER_1_0);
    assert_eq!(Gamma::Power(1.0).build_lut(), goldens::GAMMA_IDENTITY);
}

#[test]
fn negative_power_clamps_to_zero() {
    // gamma.Power clamps the exponent at construction; x^0 = 1 (pow(0,0)=1
    // in IEEE and CPython alike), so every entry saturates.
    assert_eq!(Gamma::Power(-3.0).build_lut(), [255u8; 256]);
}
