// GENERATED by tests/gen_goldens.py -- do not edit by hand.
//
// Values produced by running the real references: tools/compile_layout.py's
// packers, tools/compile_fonts.py's font builder, display.py's own CPython
// _dim_frame, and the independent `qrcode` package.
#![allow(dead_code)]

pub struct PackedCase {
    pub name: &'static str,
    pub width: usize,
    pub height: usize,
    /// Row-major palette indices that went in.
    pub indices: &'static [u8],
    /// The packed bytes that came out.
    pub packed: &'static [u8],
}

pub struct GlyphGolden {
    pub codepoint: u32,
    pub width: i32,
    pub bits: &'static [u8],
}

pub struct FontGolden {
    pub name: &'static str,
    pub height: i32,
    /// FNV-1a over every codepoint 32..=255 resolved to `(u16 width, bits)` and
    /// concatenated — the whole table, reachable through the public API.
    pub glyphs_fnv: u64,
    pub glyphs: &'static [GlyphGolden],
}

pub struct PulseCase {
    pub step: u32,
    pub packed: u16,
}

pub struct DimCase {
    /// Index into the fade ladder.
    pub step: usize,
    pub dimmed: &'static [u8],
}

/// FNV-1a, 64-bit — the digest the font goldens are recorded with.
pub fn fnv1a64(data: &[u8]) -> u64 {
    let mut value: u64 = 0xCBF2_9CE4_8422_2325;
    for byte in data {
        value = (value ^ *byte as u64).wrapping_mul(0x100_0000_01B3);
    }
    value
}

/// Index patterns packed by `tools/compile_layout.py`'s `pack_*`
/// functions — the normative definition of each format's bit order.
pub const PACKED_CASES: &[PackedCase] = &[
    PackedCase {
        name: "mono_11x3",
        width: 11,
        height: 3,
        indices: &[
            0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01,
            0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01,
            0x00, 0x01, 0x00, 0x01, 0x00,
        ],
        packed: &[0x55, 0x40, 0xaa, 0xa0, 0x55, 0x40],
    },
    PackedCase {
        name: "gs2_7x2",
        width: 7,
        height: 2,
        indices: &[
            0x00, 0x03, 0x02, 0x01, 0x00, 0x03, 0x02, 0x01, 0x00, 0x03, 0x02, 0x01, 0x00, 0x03,
        ],
        packed: &[0x6c, 0x2c, 0xb1, 0x31],
    },
    PackedCase {
        name: "gs4_5x2",
        width: 5,
        height: 2,
        indices: &[0x00, 0x05, 0x0a, 0x0f, 0x04, 0x01, 0x06, 0x0b, 0x00, 0x05],
        packed: &[0x05, 0xaf, 0x40, 0x16, 0xb0, 0x50],
    },
    PackedCase {
        name: "gs8_3x3",
        width: 3,
        height: 3,
        indices: &[0x00, 0x07, 0x0e, 0x0d, 0x14, 0x1b, 0x1a, 0x21, 0x28],
        packed: &[0x00, 0x07, 0x0e, 0x0d, 0x14, 0x1b, 0x1a, 0x21, 0x28],
    },
    PackedCase {
        name: "gs4_rows_5x2",
        width: 5,
        height: 2,
        indices: &[0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a],
        packed: &[0x12, 0x34, 0x50, 0x67, 0x89, 0xa0],
    },
    PackedCase {
        name: "gs2_leftmost",
        width: 4,
        height: 1,
        indices: &[0x01, 0x00, 0x00, 0x00],
        packed: &[0x01],
    },
    PackedCase {
        name: "gs4_leftmost",
        width: 2,
        height: 1,
        indices: &[0x0a, 0x00],
        packed: &[0xa0],
    },
];

/// A 3x2 RGB565 sprite: the packed little-endian bytes and the colors
/// they must read back as.
pub const RGB565_PACKED: &[u8] = &[
    0x00, 0xf8, 0xe0, 0x07, 0x1f, 0x00, 0xff, 0xff, 0x00, 0x00, 0xaa, 0x11,
];
pub const RGB565_COLORS: &[u16] = &[0xf800, 0x07e0, 0x001f, 0xffff, 0x0000, 0x11aa];

/// Glyph tables as `tools/compile_fonts.py` builds them, one entry per
/// font in the order `tests/fonts.rs` pairs them with.
pub const FONTS: &[FontGolden] = &[
    FontGolden {
        name: "UNSCII_8",
        height: 8,
        glyphs_fnv: 0xfd56285aafd04491,
        glyphs: &[
            GlyphGolden {
                codepoint: 32,
                width: 8,
                bits: &[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
            },
            GlyphGolden {
                codepoint: 48,
                width: 8,
                bits: &[0x3c, 0x66, 0x6e, 0x76, 0x66, 0x66, 0x3c, 0x00],
            },
            GlyphGolden {
                codepoint: 65,
                width: 8,
                bits: &[0x18, 0x3c, 0x66, 0x66, 0x7e, 0x66, 0x66, 0x00],
            },
            GlyphGolden {
                codepoint: 63,
                width: 8,
                bits: &[0x3c, 0x66, 0x06, 0x0c, 0x18, 0x00, 0x18, 0x00],
            },
            GlyphGolden {
                codepoint: 233,
                width: 8,
                bits: &[0x0e, 0x00, 0x3c, 0x66, 0x7e, 0x60, 0x3c, 0x00],
            },
            GlyphGolden {
                codepoint: 241,
                width: 8,
                bits: &[0x76, 0xdc, 0x00, 0x7c, 0x66, 0x66, 0x66, 0x00],
            },
            GlyphGolden {
                codepoint: 127,
                width: 8,
                bits: &[0x3c, 0x66, 0x06, 0x0c, 0x18, 0x00, 0x18, 0x00],
            },
            GlyphGolden {
                codepoint: 255,
                width: 8,
                bits: &[0x66, 0x00, 0x66, 0x66, 0x66, 0x3e, 0x06, 0x3c],
            },
        ],
    },
    FontGolden {
        name: "UNSCII_16",
        height: 16,
        glyphs_fnv: 0x84d0c19fe09a394f,
        glyphs: &[
            GlyphGolden {
                codepoint: 32,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 48,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x38, 0x6c, 0xc6, 0xc6, 0xce, 0xd6, 0xe6, 0xc6, 0xc6, 0x6c, 0x38,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 65,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x18, 0x3c, 0x66, 0x66, 0x66, 0x7e, 0x66, 0x66, 0x66, 0x66, 0x66,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 63,
                width: 8,
                bits: &[
                    0x00, 0x3c, 0x66, 0x66, 0x06, 0x0c, 0x18, 0x18, 0x18, 0x00, 0x00, 0x18, 0x18,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 233,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x0c, 0x18, 0x00, 0x00, 0x3c, 0x66, 0x66, 0x7e, 0x60, 0x60, 0x3c,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 241,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x76, 0xdc, 0x00, 0x00, 0x7c, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 127,
                width: 8,
                bits: &[
                    0x00, 0x3c, 0x66, 0x66, 0x06, 0x0c, 0x18, 0x18, 0x18, 0x00, 0x00, 0x18, 0x18,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 255,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x66, 0x66, 0x00, 0x00, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x3e,
                    0x06, 0x06, 0x3c,
                ],
            },
        ],
    },
    FontGolden {
        name: "SPLEEN_5X8",
        height: 8,
        glyphs_fnv: 0x556f42a8c652887d,
        glyphs: &[
            GlyphGolden {
                codepoint: 32,
                width: 5,
                bits: &[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
            },
            GlyphGolden {
                codepoint: 48,
                width: 5,
                bits: &[0x00, 0x60, 0x90, 0xb0, 0xd0, 0x90, 0x60, 0x00],
            },
            GlyphGolden {
                codepoint: 65,
                width: 5,
                bits: &[0x00, 0x60, 0x90, 0x90, 0xf0, 0x90, 0x90, 0x00],
            },
            GlyphGolden {
                codepoint: 63,
                width: 5,
                bits: &[0x60, 0x90, 0x10, 0x20, 0x40, 0x00, 0x40, 0x00],
            },
            GlyphGolden {
                codepoint: 233,
                width: 5,
                bits: &[0x00, 0x00, 0x70, 0x90, 0xf0, 0x80, 0x70, 0x00],
            },
            GlyphGolden {
                codepoint: 241,
                width: 5,
                bits: &[0x00, 0x00, 0xe0, 0x90, 0x90, 0x90, 0x90, 0x00],
            },
            GlyphGolden {
                codepoint: 127,
                width: 5,
                bits: &[0x60, 0x90, 0x10, 0x20, 0x40, 0x00, 0x40, 0x00],
            },
            GlyphGolden {
                codepoint: 255,
                width: 5,
                bits: &[0x00, 0x00, 0x90, 0x90, 0x90, 0x70, 0x10, 0xe0],
            },
        ],
    },
];

/// `display._dim_frame`'s CPython branch, run over a fixed pseudorandom
/// buffer at each rung of the fade ladder.
pub const DIM_SOURCE: &[u8] = &[
    0xa1, 0x4f, 0x01, 0xfc, 0x14, 0x6c, 0xef, 0x3e, 0x53, 0x9b, 0x04, 0xa2, 0xe0, 0xff, 0x85, 0xaa,
    0x37, 0x70, 0xf5, 0xe2, 0xea, 0x90, 0x99, 0x3a, 0x59, 0xc9, 0x1e, 0xe5, 0x88, 0x1a, 0xee, 0xd1,
    0x8e, 0xe8, 0xe2, 0xd5, 0xd5, 0x86, 0xe4, 0x16, 0xcf, 0x0e, 0xac, 0x46, 0xef, 0xdc, 0x3c, 0x79,
    0xc0, 0x42, 0x45, 0x4d, 0x49, 0x59, 0xc2, 0xa2, 0xca, 0x9d, 0xaf, 0x8a, 0xac, 0xf0, 0x40, 0x0d,
];

pub const DIM_CASES: &[DimCase] = &[
    DimCase {
        step: 0,
        dimmed: &[
            0x80, 0x3e, 0x80, 0xcb, 0x91, 0x53, 0xcb, 0x25, 0xcf, 0x7a, 0xc3, 0x89, 0xa0, 0xce,
            0x23, 0x8a, 0x12, 0x58, 0x51, 0xc2, 0x88, 0x78, 0x35, 0x22, 0x15, 0xa9, 0x79, 0xc4,
            0x27, 0x0a, 0x6b, 0xb1, 0x6b, 0xc0, 0xe1, 0xb4, 0xd1, 0x75, 0xc3, 0x0d, 0xcb, 0x05,
            0xaa, 0x3d, 0x0b, 0xb4, 0xf8, 0x58, 0x40, 0x3a, 0x83, 0x3c, 0x07, 0x41, 0x41, 0x8a,
            0xe8, 0x7c, 0x2b, 0x72, 0x6a, 0xc8, 0x80, 0x04,
        ],
    },
    DimCase {
        step: 1,
        dimmed: &[
            0xa0, 0x35, 0x00, 0xb3, 0x0f, 0x4b, 0x0a, 0x25, 0x6d, 0x6a, 0x83, 0x79, 0xc0, 0xb5,
            0xe3, 0x79, 0x10, 0x50, 0x0f, 0xaa, 0x87, 0x68, 0xf2, 0x21, 0xf2, 0x90, 0xd6, 0xab,
            0xe6, 0x09, 0x4a, 0x99, 0x6a, 0xa8, 0x41, 0x9c, 0x0f, 0x65, 0x03, 0x0d, 0x0a, 0x05,
            0xe9, 0x34, 0x8a, 0x9b, 0xd5, 0x50, 0x00, 0x32, 0xe3, 0x33, 0xe6, 0x38, 0x01, 0x7a,
            0x47, 0x6c, 0xea, 0x61, 0x69, 0xb0, 0xe0, 0x03,
        ],
    },
    DimCase {
        step: 2,
        dimmed: &[
            0xa0, 0x2c, 0x80, 0x92, 0x8c, 0x3a, 0x28, 0x1c, 0x0b, 0x5a, 0x42, 0x61, 0xc0, 0x94,
            0x82, 0x61, 0x0d, 0x40, 0xac, 0x89, 0x66, 0x58, 0x8f, 0x19, 0xcf, 0x78, 0x32, 0x8b,
            0x85, 0x09, 0x08, 0x81, 0x48, 0x88, 0x81, 0x83, 0x2c, 0x54, 0x22, 0x0c, 0x28, 0x04,
            0x07, 0x2c, 0xe8, 0x82, 0xb1, 0x40, 0xa0, 0x29, 0x42, 0x2b, 0xc5, 0x30, 0xa1, 0x61,
            0x86, 0x5b, 0x88, 0x51, 0x47, 0x90, 0x40, 0x03,
        ],
    },
    DimCase {
        step: 3,
        dimmed: &[
            0xc0, 0x23, 0x00, 0x7a, 0x0a, 0x32, 0x67, 0x1b, 0xa9, 0x49, 0x02, 0x51, 0xe0, 0x7b,
            0x42, 0x51, 0x0b, 0x38, 0x6a, 0x71, 0x65, 0x48, 0x4c, 0x19, 0xac, 0x60, 0x8f, 0x72,
            0x44, 0x09, 0xe7, 0x68, 0x47, 0x70, 0xe1, 0x6a, 0x6a, 0x43, 0x62, 0x0b, 0x67, 0x03,
            0x46, 0x23, 0x67, 0x6a, 0x8e, 0x38, 0x60, 0x21, 0xa2, 0x22, 0xa4, 0x28, 0x61, 0x51,
            0xe5, 0x4a, 0x47, 0x41, 0x46, 0x78, 0xa0, 0x02,
        ],
    },
];

/// The count-dot pulse, one entry per step of the triangle wave, as
/// the preview's stand-in for `hub75.native.pack_hsv_to_rgb565` packs
/// it. `step` is the triangle's value; the saturation and brightness
/// the renderer derives from it are part of what is being checked.
pub const PULSE_CASES: &[PulseCase] = &[
    PulseCase {
        step: 0,
        packed: 0xbdf7,
    },
    PulseCase {
        step: 1,
        packed: 0xbdf7,
    },
    PulseCase {
        step: 2,
        packed: 0xbdf7,
    },
    PulseCase {
        step: 3,
        packed: 0xbdf7,
    },
    PulseCase {
        step: 4,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 5,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 6,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 7,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 8,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 9,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 10,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 11,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 12,
        packed: 0xc618,
    },
    PulseCase {
        step: 13,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 14,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 15,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 16,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 17,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 18,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 19,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 20,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 21,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 22,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 23,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 24,
        packed: 0xc618,
    },
    PulseCase {
        step: 25,
        packed: 0xc618,
    },
    PulseCase {
        step: 26,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 27,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 28,
        packed: 0xc618,
    },
    PulseCase {
        step: 29,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 30,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 31,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 32,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 33,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 34,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 35,
        packed: 0xc5f7,
    },
    PulseCase {
        step: 36,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 37,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 38,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 39,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 40,
        packed: 0xce18,
    },
    PulseCase {
        step: 41,
        packed: 0xce18,
    },
    PulseCase {
        step: 42,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 43,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 44,
        packed: 0xce18,
    },
    PulseCase {
        step: 45,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 46,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 47,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 48,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 49,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 50,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 51,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 52,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 53,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 54,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 55,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 56,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 57,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 58,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 59,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 60,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 61,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 62,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 63,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 64,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 65,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 66,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 67,
        packed: 0xcdf7,
    },
    PulseCase {
        step: 68,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 69,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 70,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 71,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 72,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 73,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 74,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 75,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 76,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 77,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 78,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 79,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 80,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 81,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 82,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 83,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 84,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 85,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 86,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 87,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 88,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 89,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 90,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 91,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 92,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 93,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 94,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 95,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 96,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 97,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 98,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 99,
        packed: 0xd5f7,
    },
    PulseCase {
        step: 100,
        packed: 0xddf7,
    },
    PulseCase {
        step: 101,
        packed: 0xddf7,
    },
    PulseCase {
        step: 102,
        packed: 0xddf7,
    },
    PulseCase {
        step: 103,
        packed: 0xddf7,
    },
    PulseCase {
        step: 104,
        packed: 0xddf7,
    },
    PulseCase {
        step: 105,
        packed: 0xddf7,
    },
    PulseCase {
        step: 106,
        packed: 0xddf7,
    },
    PulseCase {
        step: 107,
        packed: 0xddf7,
    },
    PulseCase {
        step: 108,
        packed: 0xddf7,
    },
    PulseCase {
        step: 109,
        packed: 0xddf7,
    },
    PulseCase {
        step: 110,
        packed: 0xddf7,
    },
    PulseCase {
        step: 111,
        packed: 0xddf7,
    },
    PulseCase {
        step: 112,
        packed: 0xddf7,
    },
    PulseCase {
        step: 113,
        packed: 0xddf7,
    },
    PulseCase {
        step: 114,
        packed: 0xddf7,
    },
    PulseCase {
        step: 115,
        packed: 0xddf7,
    },
    PulseCase {
        step: 116,
        packed: 0xddf7,
    },
    PulseCase {
        step: 117,
        packed: 0xddf7,
    },
    PulseCase {
        step: 118,
        packed: 0xddf7,
    },
    PulseCase {
        step: 119,
        packed: 0xddf7,
    },
    PulseCase {
        step: 120,
        packed: 0xddf7,
    },
    PulseCase {
        step: 121,
        packed: 0xddf7,
    },
    PulseCase {
        step: 122,
        packed: 0xddf7,
    },
    PulseCase {
        step: 123,
        packed: 0xddf7,
    },
    PulseCase {
        step: 124,
        packed: 0xddf7,
    },
    PulseCase {
        step: 125,
        packed: 0xddf7,
    },
    PulseCase {
        step: 126,
        packed: 0xddf7,
    },
    PulseCase {
        step: 127,
        packed: 0xddf7,
    },
    PulseCase {
        step: 128,
        packed: 0xddf7,
    },
    PulseCase {
        step: 129,
        packed: 0xddf7,
    },
    PulseCase {
        step: 130,
        packed: 0xddf7,
    },
    PulseCase {
        step: 131,
        packed: 0xddf7,
    },
    PulseCase {
        step: 132,
        packed: 0xe5f7,
    },
    PulseCase {
        step: 133,
        packed: 0xe5f7,
    },
    PulseCase {
        step: 134,
        packed: 0xe5f7,
    },
    PulseCase {
        step: 135,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 136,
        packed: 0xe5f7,
    },
    PulseCase {
        step: 137,
        packed: 0xe5f7,
    },
    PulseCase {
        step: 138,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 139,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 140,
        packed: 0xe5f7,
    },
    PulseCase {
        step: 141,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 142,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 143,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 144,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 145,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 146,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 147,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 148,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 149,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 150,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 151,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 152,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 153,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 154,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 155,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 156,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 157,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 158,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 159,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 160,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 161,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 162,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 163,
        packed: 0xe5d7,
    },
    PulseCase {
        step: 164,
        packed: 0xedd7,
    },
    PulseCase {
        step: 165,
        packed: 0xedd7,
    },
    PulseCase {
        step: 166,
        packed: 0xedd7,
    },
    PulseCase {
        step: 167,
        packed: 0xedd7,
    },
    PulseCase {
        step: 168,
        packed: 0xedd7,
    },
    PulseCase {
        step: 169,
        packed: 0xedd7,
    },
    PulseCase {
        step: 170,
        packed: 0xedd7,
    },
    PulseCase {
        step: 171,
        packed: 0xedd7,
    },
    PulseCase {
        step: 172,
        packed: 0xedd7,
    },
    PulseCase {
        step: 173,
        packed: 0xedd7,
    },
    PulseCase {
        step: 174,
        packed: 0xedd7,
    },
    PulseCase {
        step: 175,
        packed: 0xedd7,
    },
    PulseCase {
        step: 176,
        packed: 0xedd7,
    },
    PulseCase {
        step: 177,
        packed: 0xedd7,
    },
    PulseCase {
        step: 178,
        packed: 0xedd7,
    },
    PulseCase {
        step: 179,
        packed: 0xedd7,
    },
    PulseCase {
        step: 180,
        packed: 0xedd7,
    },
    PulseCase {
        step: 181,
        packed: 0xedd7,
    },
    PulseCase {
        step: 182,
        packed: 0xedd7,
    },
    PulseCase {
        step: 183,
        packed: 0xedb6,
    },
    PulseCase {
        step: 184,
        packed: 0xedd7,
    },
    PulseCase {
        step: 185,
        packed: 0xedd7,
    },
    PulseCase {
        step: 186,
        packed: 0xedb6,
    },
    PulseCase {
        step: 187,
        packed: 0xedb6,
    },
    PulseCase {
        step: 188,
        packed: 0xedd7,
    },
    PulseCase {
        step: 189,
        packed: 0xedb6,
    },
    PulseCase {
        step: 190,
        packed: 0xedb6,
    },
    PulseCase {
        step: 191,
        packed: 0xedb6,
    },
    PulseCase {
        step: 192,
        packed: 0xedb6,
    },
    PulseCase {
        step: 193,
        packed: 0xedb6,
    },
    PulseCase {
        step: 194,
        packed: 0xedb6,
    },
    PulseCase {
        step: 195,
        packed: 0xedb6,
    },
    PulseCase {
        step: 196,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 197,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 198,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 199,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 200,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 201,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 202,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 203,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 204,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 205,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 206,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 207,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 208,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 209,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 210,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 211,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 212,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 213,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 214,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 215,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 216,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 217,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 218,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 219,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 220,
        packed: 0xf5b6,
    },
    PulseCase {
        step: 221,
        packed: 0xf596,
    },
    PulseCase {
        step: 222,
        packed: 0xf596,
    },
    PulseCase {
        step: 223,
        packed: 0xf596,
    },
    PulseCase {
        step: 224,
        packed: 0xf596,
    },
    PulseCase {
        step: 225,
        packed: 0xf596,
    },
    PulseCase {
        step: 226,
        packed: 0xf596,
    },
    PulseCase {
        step: 227,
        packed: 0xf596,
    },
    PulseCase {
        step: 228,
        packed: 0xfd96,
    },
    PulseCase {
        step: 229,
        packed: 0xfd96,
    },
    PulseCase {
        step: 230,
        packed: 0xfd96,
    },
    PulseCase {
        step: 231,
        packed: 0xfd96,
    },
    PulseCase {
        step: 232,
        packed: 0xfd96,
    },
    PulseCase {
        step: 233,
        packed: 0xfd96,
    },
    PulseCase {
        step: 234,
        packed: 0xfd96,
    },
    PulseCase {
        step: 235,
        packed: 0xfd96,
    },
    PulseCase {
        step: 236,
        packed: 0xfd96,
    },
    PulseCase {
        step: 237,
        packed: 0xfd96,
    },
    PulseCase {
        step: 238,
        packed: 0xfd96,
    },
    PulseCase {
        step: 239,
        packed: 0xfd96,
    },
    PulseCase {
        step: 240,
        packed: 0xfd96,
    },
    PulseCase {
        step: 241,
        packed: 0xfd96,
    },
    PulseCase {
        step: 242,
        packed: 0xfd96,
    },
    PulseCase {
        step: 243,
        packed: 0xfd96,
    },
    PulseCase {
        step: 244,
        packed: 0xfd96,
    },
    PulseCase {
        step: 245,
        packed: 0xfd96,
    },
    PulseCase {
        step: 246,
        packed: 0xfd96,
    },
    PulseCase {
        step: 247,
        packed: 0xfd96,
    },
    PulseCase {
        step: 248,
        packed: 0xfd96,
    },
    PulseCase {
        step: 249,
        packed: 0xfd96,
    },
    PulseCase {
        step: 250,
        packed: 0xfd96,
    },
    PulseCase {
        step: 251,
        packed: 0xfd96,
    },
    PulseCase {
        step: 252,
        packed: 0xfd96,
    },
    PulseCase {
        step: 253,
        packed: 0xfd75,
    },
    PulseCase {
        step: 254,
        packed: 0xfd75,
    },
    PulseCase {
        step: 255,
        packed: 0xfd75,
    },
    PulseCase {
        step: 256,
        packed: 0xfd75,
    },
];

/// The setup QR's payload, and the symbol the `qrcode` package
/// produces for it at medium ECC in byte mode — one matrix per mask
/// pattern. See gen_goldens.py's `qr_golden` for what is pinned and why.
pub const QR_PAYLOAD: &str = "WIFI:T:nopass;S:pico-scoreboard;;";
pub const QR_VERSION: u8 = 3;
pub const QR_SIZE: i32 = 29;
pub const QR_BY_MASK: &[&[&[bool]]] = &[
    &[
        &[
            true, true, true, true, true, true, true, false, false, true, true, false, true, false,
            true, false, false, false, true, true, false, false, true, true, true, true, true,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, false, false, false, true,
            true, false, false, false, false, false, true, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, false, true,
            false, false, true, false, false, false, true, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, false, false,
            true, false, false, true, false, true, true, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, false,
            true, false, false, true, true, true, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, true, true, false,
            false, true, true, true, false, true, true, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, false, true, false, true, true, true, true, false, false, false, false,
            false, false, false, false,
        ],
        &[
            true, false, true, false, true, false, true, false, false, false, true, false, true,
            false, false, false, true, true, false, true, true, false, false, false, true, false,
            false, true, false,
        ],
        &[
            false, false, false, false, false, true, false, false, false, true, true, false, true,
            true, false, true, true, true, true, false, false, false, true, false, false, true,
            true, true, false,
        ],
        &[
            true, false, true, false, false, true, true, false, false, true, true, true, false,
            false, true, true, true, true, true, false, false, false, true, true, false, true,
            true, true, true,
        ],
        &[
            false, true, true, true, true, true, false, true, true, false, false, false, false,
            true, true, false, true, true, false, false, true, false, true, true, false, true,
            false, true, true,
        ],
        &[
            false, false, false, false, true, false, true, false, true, false, false, false, true,
            false, true, true, true, true, false, true, true, false, true, true, false, true,
            false, true, true,
        ],
        &[
            false, true, false, true, true, true, false, true, true, true, true, false, true,
            false, true, true, false, true, false, false, true, false, true, false, false, true,
            true, true, false,
        ],
        &[
            true, false, true, false, false, true, true, true, true, true, true, false, true, true,
            false, false, false, false, false, false, false, false, false, true, true, false,
            false, true, true,
        ],
        &[
            false, false, false, true, true, true, false, false, false, true, false, true, true,
            false, false, false, false, true, true, false, false, false, true, true, false, false,
            false, false, false,
        ],
        &[
            true, true, true, true, true, false, true, false, true, true, false, false, false,
            false, false, true, false, true, false, false, true, true, true, false, false, true,
            true, false, false,
        ],
        &[
            false, true, false, true, false, true, false, true, false, true, false, false, true,
            true, false, false, false, true, false, false, true, false, false, false, false, false,
            false, true, false,
        ],
        &[
            true, false, false, true, true, false, true, true, true, false, false, true, true,
            false, true, false, false, true, true, false, false, false, true, false, true, false,
            true, true, true,
        ],
        &[
            false, true, true, true, true, true, false, true, false, true, true, false, true, true,
            true, false, false, true, false, true, false, false, true, true, false, true, false,
            false, true,
        ],
        &[
            true, false, true, true, true, true, true, true, false, false, true, false, false,
            false, true, true, false, true, false, true, true, true, true, true, true, true, false,
            true, true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, true, false, false,
            false, true, false, false, false, false, true, true, false, false, false, true, true,
            true, false, false,
        ],
        &[
            true, true, true, true, true, true, true, false, false, true, false, false, true, true,
            false, false, true, true, false, true, true, false, true, false, true, false, false,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, false, true, true,
            false, false, true, true, true, true, false, true, false, false, false, true, false,
            false, false, false,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, true, false, true,
            false, false, false, true, true, false, false, true, true, true, true, true, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, false, false,
            true, false, false, true, true, false, true, false, true, false, false, true, false,
            true, true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, true, false, false,
            false, true, false, true, false, true, false, true, true, false, true, true, false,
            false, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, false, false,
            true, false, false, false, true, true, false, true, true, true, false, true, false,
            false, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, false, false, true, true,
            false, false, false, true, false, true, true, false, false, true, false, false, false,
            true, true,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, true, false, true, true, true, true,
            true, true, false, true, true, false, false, false, true, true, true, true, true, true,
            true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            false, false, true, false, true, false, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, true, true,
            false, false, false, true, false, false, true, false, true, false, true, true, true,
            false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, false,
            false, false, true, true, true, true, false, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, false, false,
            false, false, true, true, false, true, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, false, true, false, false,
            true, true, false, true, true, true, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, false, false, false, false,
            false, true, false, false, false, false, true, false, true, false, false, false, false,
            false, false, false, false,
        ],
        &[
            true, false, true, false, false, false, true, true, false, true, true, true, true,
            true, false, true, true, false, false, false, true, false, false, true, false, false,
            true, false, true,
        ],
        &[
            false, true, false, true, false, false, false, true, false, false, true, true, true,
            false, false, false, true, false, true, true, false, true, true, true, false, false,
            true, false, false,
        ],
        &[
            true, true, true, true, false, false, true, true, false, false, true, false, false,
            true, true, false, true, false, true, true, false, true, true, false, false, false,
            true, false, true,
        ],
        &[
            false, false, true, false, true, false, false, false, true, true, false, true, false,
            false, true, true, true, false, false, true, true, true, true, false, false, false,
            false, false, true,
        ],
        &[
            false, true, false, true, true, true, true, true, true, true, false, true, true, true,
            true, false, true, false, false, false, true, true, true, false, false, false, false,
            false, true,
        ],
        &[
            false, false, false, false, true, false, false, false, true, false, true, true, true,
            true, true, false, false, false, false, true, true, true, true, true, false, false,
            true, false, false,
        ],
        &[
            true, true, true, true, false, false, true, false, true, false, true, true, true,
            false, false, true, false, true, false, true, false, true, false, false, true, true,
            false, false, true,
        ],
        &[
            false, true, false, false, true, false, false, true, false, false, false, false, true,
            true, false, true, false, false, true, true, false, true, true, false, false, true,
            false, true, false,
        ],
        &[
            true, false, true, false, true, true, true, true, true, false, false, true, false,
            true, false, false, false, false, false, true, true, false, true, true, false, false,
            true, true, false,
        ],
        &[
            false, false, false, false, false, false, false, false, false, false, false, true,
            true, false, false, true, false, false, false, true, true, true, false, true, false,
            true, false, false, false,
        ],
        &[
            true, true, false, false, true, true, true, false, true, true, false, false, true,
            true, true, true, false, false, true, true, false, true, true, true, true, true, true,
            false, true,
        ],
        &[
            false, false, true, false, true, false, false, false, false, false, true, true, true,
            false, true, true, false, false, false, false, false, true, true, false, false, false,
            false, true, true,
        ],
        &[
            true, true, true, false, true, false, true, false, false, true, true, true, false,
            true, true, false, false, false, false, false, true, true, true, true, true, false,
            false, false, true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, true, true, false,
            true, true, true, false, true, false, false, true, false, false, false, true, false,
            true, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, false, true, true, false,
            false, true, true, false, false, false, true, false, true, false, true, true, false,
            false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, false, true,
            true, false, false, true, false, true, true, true, false, false, false, true, true,
            false, true, false,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, true, true,
            true, false, true, true, false, false, true, true, true, true, true, true, true, false,
            true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, false,
            false, false, true, true, false, false, false, false, false, false, true, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, true, true, true, false, false, false, true, true, false,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, true, true, false,
            false, false, true, false, false, true, true, true, false, true, true, true, true,
            false, false, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, true, false, true, true, false,
            false, true, false, false, false, false, true, true, false, false, false, true, false,
            false, true,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, false, false, false, false, true,
            false, false, true, true, false, true, true, true, false, true, true, true, true, true,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, false, true, false,
            false, false, false, false, true, true, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, true,
            false, true, false, true, false, false, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, true,
            false, false, false, true, true, false, false, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, false, true, false,
            true, true, true, false, true, true, true, true, false, true, false, true, true, true,
            false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, true, false, true,
            true, true, true, true, true, false, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, false, false, true,
            true, false, true, false, false, false, false, true, false, false, false, false, false,
            false, false, false,
        ],
        &[
            true, false, true, true, true, true, true, false, false, true, false, false, true,
            false, true, true, false, true, false, true, false, false, true, true, true, true,
            true, false, false,
        ],
        &[
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            false, false, true, true, false, false, true, false, false, true, true, true, false,
            true, true, false,
        ],
        &[
            true, false, false, true, true, true, true, false, true, false, false, true, false,
            false, false, false, false, true, true, false, true, true, false, true, false, true,
            false, false, false,
        ],
        &[
            true, false, true, true, true, false, false, false, true, false, false, true, true,
            false, true, false, true, false, true, true, true, false, true, false, true, false,
            false, true, true,
        ],
        &[
            false, false, true, true, false, false, true, false, false, true, true, false, true,
            false, false, false, false, true, false, true, false, true, false, true, false, true,
            true, false, false,
        ],
        &[
            true, false, false, true, true, false, false, false, true, true, true, true, false,
            true, true, true, false, false, true, true, true, false, true, true, true, false, true,
            true, false,
        ],
        &[
            true, false, false, true, true, true, true, true, false, false, false, false, true,
            true, true, true, true, false, false, false, true, true, true, true, true, false, true,
            false, false,
        ],
        &[
            true, true, false, true, true, false, false, true, false, true, false, false, false,
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            false, false, false,
        ],
        &[
            true, true, false, false, false, false, true, false, false, false, true, false, false,
            false, true, false, true, true, false, false, false, false, false, false, false, true,
            false, true, true,
        ],
        &[
            true, false, false, true, false, false, false, false, false, true, false, true, false,
            false, false, false, false, false, true, true, true, false, false, true, true, true,
            false, true, false,
        ],
        &[
            true, false, true, false, false, false, true, true, false, true, true, true, true,
            false, false, true, true, true, true, false, true, true, false, false, true, false,
            false, false, false,
        ],
        &[
            true, false, true, true, true, false, false, false, false, true, true, true, false,
            false, true, false, false, false, true, false, false, false, true, false, true, false,
            false, false, true,
        ],
        &[
            true, false, false, false, false, true, true, true, true, true, false, false, false,
            false, false, false, true, true, false, true, true, true, true, true, true, true, true,
            false, false,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, true, true, true,
            true, true, false, false, true, true, false, true, false, false, false, true, false,
            true, false, false,
        ],
        &[
            true, true, true, true, true, true, true, false, false, false, true, false, true, true,
            true, true, false, true, false, true, true, false, true, false, true, false, true,
            false, false,
        ],
        &[
            true, false, false, false, false, false, true, false, true, false, false, false, false,
            true, false, true, true, false, false, true, true, false, false, false, true, true,
            false, false, false,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, true,
            false, true, true, false, true, false, false, true, true, true, true, true, false,
            true, true, false,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, true,
            false, false, false, true, false, true, false, false, true, false, true, false, true,
            true, true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, false,
            false, false, true, false, false, true, false, false, false, true, true, true, false,
            true, true, false,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, true, true,
            false, false, false, false, false, false, true, true, true, true, true, false, true,
            false, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, true, true, false, true, true,
            true, true, true, true, false, true, false, true, true, true, false, false, true,
            false, false,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, true, false, false, false, true,
            false, false, true, true, false, true, true, true, false, true, true, true, true, true,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, false, false, true,
            false, true, true, false, false, false, false, false, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, false, false,
            true, true, true, false, false, true, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, true,
            false, false, false, true, true, false, false, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, false, false, true,
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, false, false,
            false, false, true, false, false, true, true, true, true, false, true, false, false,
            false, false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, false, true,
            false, true, true, false, false, true, true, false, false, false, false, false, false,
            false, false, false, false,
        ],
        &[
            true, false, true, true, false, true, true, true, false, false, true, false, false,
            true, true, false, true, true, true, false, false, false, true, false, false, true,
            false, true, true,
        ],
        &[
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            false, false, true, true, false, false, true, false, false, true, true, true, false,
            true, true, false,
        ],
        &[
            false, false, true, false, true, false, true, false, false, true, false, false, true,
            false, true, true, false, false, false, false, false, false, false, false, true, true,
            true, true, false,
        ],
        &[
            false, true, true, false, false, false, false, true, true, true, true, true, false,
            true, true, true, false, false, false, false, true, true, false, false, false, true,
            false, false, false,
        ],
        &[
            false, false, true, true, false, false, true, false, false, true, true, false, true,
            false, false, false, false, true, false, true, false, true, false, true, false, true,
            true, false, false,
        ],
        &[
            false, false, true, false, true, true, false, false, false, false, true, false, true,
            true, false, false, false, true, false, true, false, true, true, false, false, false,
            false, false, false,
        ],
        &[
            false, true, false, false, false, true, true, false, false, true, true, false, false,
            false, true, false, false, false, true, true, true, false, false, true, false, true,
            true, true, true,
        ],
        &[
            true, true, false, true, true, false, false, true, false, true, false, false, false,
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            false, false, false,
        ],
        &[
            false, true, true, true, false, true, true, false, true, true, true, true, true, false,
            false, true, true, false, true, false, true, true, false, true, true, true, true,
            false, true,
        ],
        &[
            false, true, false, false, true, false, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, true, true, true, true, false, false,
            false, false, true,
        ],
        &[
            true, false, true, false, false, false, true, true, false, true, true, true, true,
            false, false, true, true, true, true, false, true, true, false, false, true, false,
            false, false, false,
        ],
        &[
            false, false, false, false, true, true, false, false, true, false, true, false, true,
            false, false, true, false, true, false, false, true, true, true, true, false, false,
            true, true, true,
        ],
        &[
            false, true, false, true, true, true, true, false, true, false, true, false, true,
            true, false, true, false, true, true, false, true, true, true, true, true, false, true,
            true, true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, true, true, true,
            true, true, false, false, true, true, false, true, false, false, false, true, false,
            true, false, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, true, true, true, false, true,
            false, false, false, false, true, true, true, false, true, false, true, false, false,
            true, false,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, true, false, true,
            false, false, false, false, false, true, false, true, false, false, false, true, false,
            false, true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, false, false, true,
            false, true, true, false, true, false, false, true, true, true, true, true, false,
            true, true, false,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, true, false, false,
            false, true, true, true, true, false, false, true, false, false, false, true, true,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, true, false, true, true,
            false, false, true, false, false, true, false, true, false, true, false, true, true,
            false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, true, true,
            false, false, false, false, false, false, true, true, true, true, true, false, true,
            false, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, true, false, true,
            false, false, true, false, true, true, true, false, true, false, true, false, false,
            true, false,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, true, true, false, false, true, true,
            true, false, true, false, true, false, false, false, true, true, true, true, true,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, true, false,
            true, true, true, false, true, true, true, false, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, true, false,
            false, true, false, false, true, true, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, false,
            false, false, false, false, false, true, false, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, true, false,
            false, false, false, false, true, true, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, false, true, false, true,
            false, false, false, true, true, false, true, false, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, true, true, false,
            true, false, true, true, true, true, false, true, false, false, false, false, false,
            false, false, false,
        ],
        &[
            true, false, false, false, true, false, true, true, true, false, false, false, true,
            true, false, false, false, true, false, false, true, true, true, true, true, true,
            false, false, true,
        ],
        &[
            true, false, true, true, false, false, false, false, true, false, true, true, false,
            true, true, false, true, false, false, false, true, true, true, true, true, true,
            false, false, false,
        ],
        &[
            false, false, false, true, false, false, true, false, true, false, true, false, true,
            false, false, false, true, false, false, false, true, true, true, false, true, true,
            false, false, true,
        ],
        &[
            false, false, true, true, false, true, false, false, true, false, true, false, false,
            false, true, false, false, true, false, true, true, false, false, true, false, false,
            false, true, false,
        ],
        &[
            false, true, false, false, false, false, true, true, true, false, true, false, true,
            true, true, true, false, true, false, false, true, false, false, true, false, false,
            false, true, false,
        ],
        &[
            true, true, true, false, true, false, false, true, false, false, true, true, false,
            false, false, false, false, false, true, false, false, true, true, true, true, true,
            false, false, false,
        ],
        &[
            false, false, false, true, false, false, true, true, false, false, true, true, false,
            true, true, true, false, true, true, false, true, true, false, false, false, false,
            true, false, true,
        ],
        &[
            false, true, false, true, false, true, false, true, false, true, true, true, true,
            true, false, false, true, true, true, true, false, false, false, true, false, true,
            false, false, true,
        ],
        &[
            true, false, true, true, false, false, true, true, true, true, true, false, false,
            true, false, true, true, true, false, true, true, true, false, false, false, false,
            true, false, true,
        ],
        &[
            true, true, true, false, false, false, false, true, true, false, false, true, false,
            true, true, true, false, false, true, false, false, true, false, true, true, false,
            true, false, false,
        ],
        &[
            false, false, true, false, true, true, true, true, false, true, false, false, false,
            false, false, true, false, false, false, false, true, true, true, true, false, false,
            false, false, true,
        ],
        &[
            false, false, true, true, false, true, false, false, false, true, false, false, true,
            false, true, false, true, true, false, false, false, false, false, true, false, false,
            false, false, false,
        ],
        &[
            true, true, true, true, false, true, true, false, false, false, false, false, false,
            true, true, true, true, true, false, false, true, true, true, true, true, false, false,
            true, false,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, true, true, true,
            false, false, true, false, true, true, true, true, false, false, false, true, true,
            false, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, false, true, false, true,
            true, true, true, false, true, true, true, false, true, false, true, false, true,
            false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, true, true,
            true, false, true, false, true, true, true, true, false, false, false, true, true,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, false, false, true,
            true, false, false, false, true, false, true, true, true, true, true, true, true,
            false, false, false,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, true, true,
            true, true, true, false, true, true, true, false, false, true, false, false, false,
            false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, true, true,
            false, false, true, true, true, false, false, false, false, false, false, false, false,
            true, true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, false, false,
            false, false, false, false, true, true, true, true, true, true, false, false, true,
            true, false, true, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            false, false, true, true, false, false, true, false, true, true, false, true, false,
            true, false,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, false, false, true, true, true, true,
            true, true, false, true, true, false, false, false, true, true, true, true, true, true,
            true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, false, true, false,
            false, false, true, false, true, true, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, true,
            false, true, false, true, false, false, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, false, true, true,
            false, true, true, false, true, false, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, false, true, false,
            true, true, true, false, true, true, true, true, false, true, false, true, true, true,
            false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, false, true,
            true, true, false, true, true, false, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, false, false,
            true, true, false, false, false, false, false, false, true, false, false, false, false,
            false, false, false, false,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, false, false, true,
            false, true, true, false, true, false, true, false, true, true, false, false, true,
            true, true, false,
        ],
        &[
            true, true, true, true, true, false, false, true, true, false, false, true, false,
            false, true, false, false, false, false, true, true, true, false, true, true, false,
            false, false, true,
        ],
        &[
            true, false, false, true, true, true, true, false, true, false, false, true, false,
            false, false, false, false, true, true, false, true, true, false, true, false, true,
            false, false, false,
        ],
        &[
            true, false, true, false, true, false, false, false, true, true, false, true, true,
            false, true, true, true, false, true, true, true, true, true, false, true, false,
            false, false, true,
        ],
        &[
            false, true, false, true, true, true, true, true, true, true, false, true, true, true,
            true, false, true, false, false, false, true, true, true, false, false, false, false,
            false, true,
        ],
        &[
            true, false, false, false, true, false, false, false, true, false, true, true, false,
            true, true, false, false, false, true, true, true, true, true, true, true, false, true,
            false, false,
        ],
        &[
            true, false, false, true, true, true, true, true, false, false, false, false, true,
            true, true, true, true, false, false, false, true, true, true, true, true, false, true,
            false, false,
        ],
        &[
            true, true, true, false, false, false, false, true, true, false, true, false, false,
            true, true, true, true, false, false, true, true, true, false, false, true, true, true,
            true, true,
        ],
        &[
            true, true, false, false, false, false, true, false, false, false, true, false, false,
            false, true, false, true, true, false, false, false, false, false, false, false, true,
            false, true, true,
        ],
        &[
            true, false, false, false, false, false, false, false, false, false, false, true,
            false, false, false, true, false, false, true, true, true, true, false, true, true,
            true, false, false, false,
        ],
        &[
            true, true, false, false, true, true, true, false, true, true, false, false, true,
            true, true, true, false, false, true, true, false, true, true, true, true, true, true,
            false, true,
        ],
        &[
            true, false, true, false, true, false, false, false, false, false, true, true, false,
            false, true, true, false, false, true, false, false, true, true, false, true, false,
            false, true, true,
        ],
        &[
            true, false, false, false, false, true, true, true, true, true, false, false, false,
            false, false, false, true, true, false, true, true, true, true, true, true, true, true,
            false, false,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, false, true, true,
            true, false, true, true, true, true, false, true, false, false, false, true, false,
            false, true, true,
        ],
        &[
            true, true, true, true, true, true, true, false, false, false, true, false, true, true,
            true, true, false, true, false, true, true, false, true, false, true, false, true,
            false, false,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, false, false,
            true, false, false, true, false, false, true, true, false, false, false, true, true,
            false, true, false,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, true, true,
            true, false, true, true, false, false, true, true, true, true, true, true, true, false,
            true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, true,
            false, false, true, true, false, true, false, false, false, false, true, false, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, false, false, false,
            false, false, true, false, false, true, false, false, false, true, true, true, false,
            true, true, false,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            false, true, true, true, false, false, true, false, false, false, true, false, true,
            true, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, true, true, false, true, true,
            true, true, true, true, false, true, false, true, true, true, false, false, true,
            false, false,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, true, false, true, true, true, true,
            true, true, false, true, true, false, false, false, true, true, true, true, true, true,
            true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, false, true, false,
            true, true, true, false, true, true, true, false, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, false, true,
            true, true, false, false, false, false, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, false, true, true,
            false, true, true, false, true, false, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, false, false, false,
            true, false, true, false, false, true, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, false, true, true,
            true, true, false, false, false, false, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, false, false, false, false,
            true, false, true, false, false, false, false, true, false, false, false, false, false,
            false, false, false, false,
        ],
        &[
            true, false, false, true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, false, false, false, true, false, false, true, false, true,
            true, true,
        ],
        &[
            true, true, true, true, true, false, false, true, true, false, false, true, false,
            false, true, false, false, false, false, true, true, true, false, true, true, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, false, false, false,
            false, true, false, false, false, true, false, false, true, false, false, false, true,
            true, false, false,
        ],
        &[
            true, false, true, false, false, true, false, false, true, true, true, false, true,
            false, true, true, false, true, true, true, true, true, false, true, true, false,
            false, false, false,
        ],
        &[
            false, true, false, true, true, true, true, true, true, true, false, true, true, true,
            true, false, true, false, false, false, true, true, true, false, false, false, false,
            false, true,
        ],
        &[
            true, true, true, false, true, false, false, true, false, false, true, true, false,
            false, false, false, false, false, true, false, false, true, true, true, true, true,
            false, false, false,
        ],
        &[
            true, true, false, true, false, true, true, false, false, false, true, false, true,
            false, true, true, false, false, false, true, true, true, false, true, true, true,
            true, false, true,
        ],
        &[
            true, true, true, false, false, false, false, true, true, false, true, false, false,
            true, true, true, true, false, false, true, true, true, false, false, true, true, true,
            true, true,
        ],
        &[
            true, true, true, false, false, true, true, false, true, false, true, true, false,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            true, true, true,
        ],
        &[
            true, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, true, true, true, true, true, true, true, true, false, true, true, false,
            false, true,
        ],
        &[
            true, true, false, false, true, true, true, false, true, true, false, false, true,
            true, true, true, false, false, true, true, false, true, true, true, true, true, true,
            false, true,
        ],
        &[
            true, true, false, false, true, false, false, true, true, false, true, true, false,
            true, false, true, false, false, true, true, true, true, true, false, true, true, true,
            true, true,
        ],
        &[
            true, true, false, false, true, true, true, false, true, true, true, false, false,
            true, false, false, false, true, false, false, true, true, true, true, true, false,
            true, false, true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, false, true, true,
            true, false, true, true, true, true, false, true, false, false, false, true, false,
            false, true, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, true, true, true,
            false, true, false, false, false, true, true, false, true, false, true, false, false,
            false, false,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, true, true, false,
            true, false, false, false, true, false, true, true, false, false, false, true, true,
            false, true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, true, true,
            false, true, true, false, false, true, true, true, true, true, true, true, false, true,
            true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, true, true, true, true,
            true, true, true, false, true, true, true, false, false, true, false, false, false,
            false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, false, false,
            true, false, true, true, false, true, true, false, false, false, true, true, true,
            true, true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            false, true, true, true, false, false, true, false, false, false, true, false, true,
            true, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, true, true, true, true, true,
            false, true, true, false, false, true, true, true, true, false, false, false, false,
            false, false,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, false, true, true, false, true, false,
            true, false, false, false, true, true, false, false, true, true, true, true, true,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, false, true,
            false, false, false, true, false, false, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, true,
            false, true, true, false, true, false, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, false, false,
            true, false, false, true, false, true, true, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, false, true, false,
            false, false, false, false, true, true, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, true, false, false,
            false, false, true, true, true, true, true, false, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, false, true, true, true, false,
            true, false, true, true, true, true, false, true, false, false, false, false, false,
            false, false, false,
        ],
        &[
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            false, true, false, true, false, false, true, false, true, false, true, false, false,
            false, false, false,
        ],
        &[
            false, false, false, false, false, true, false, false, false, true, true, false, true,
            true, false, true, true, true, true, false, false, false, true, false, false, true,
            true, true, false,
        ],
        &[
            true, true, true, false, true, true, true, true, false, true, false, true, false, true,
            true, true, false, true, true, true, false, false, false, true, false, false, true,
            true, false,
        ],
        &[
            false, true, false, true, true, false, false, true, false, false, false, true, false,
            true, false, false, true, false, false, false, false, false, true, false, false, true,
            true, true, true,
        ],
        &[
            false, false, false, false, true, false, true, false, true, false, false, false, true,
            false, true, true, true, true, false, true, true, false, true, true, false, true,
            false, true, true,
        ],
        &[
            false, false, false, true, false, true, false, false, true, true, false, false, true,
            true, true, true, true, true, false, true, true, false, false, false, false, false,
            true, true, true,
        ],
        &[
            true, false, false, false, false, false, true, true, false, true, true, true, true,
            true, true, false, false, true, false, false, true, false, false, false, true, false,
            true, true, true,
        ],
        &[
            false, false, false, true, true, true, false, false, false, true, false, true, true,
            false, false, false, false, true, true, false, false, false, true, true, false, false,
            false, false, false,
        ],
        &[
            true, false, true, true, false, false, true, true, true, true, true, false, false,
            true, false, true, true, true, false, true, true, true, false, false, false, false,
            true, false, true,
        ],
        &[
            false, true, true, true, false, false, false, true, true, true, false, true, true,
            true, true, false, false, false, false, false, false, false, false, true, false, false,
            true, true, false,
        ],
        &[
            true, false, false, true, true, false, true, true, true, false, false, true, true,
            false, true, false, false, true, true, false, false, false, true, false, true, false,
            true, true, true,
        ],
        &[
            false, false, true, true, false, true, false, false, false, true, false, false, true,
            false, true, false, true, true, false, false, false, false, false, true, false, false,
            false, false, false,
        ],
        &[
            true, false, false, true, true, false, true, true, true, false, true, true, false,
            false, false, true, false, false, false, true, true, true, true, true, true, true,
            true, true, true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, true, false, false,
            false, true, false, false, false, false, true, true, false, false, false, true, true,
            true, false, false,
        ],
        &[
            true, true, true, true, true, true, true, false, false, true, true, false, true, false,
            false, false, false, true, false, false, true, false, true, false, true, true, false,
            true, false,
        ],
        &[
            true, false, false, false, false, false, true, false, true, false, false, false, true,
            false, true, true, true, false, true, false, true, false, false, false, true, false,
            true, false, false,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, false, true,
            false, false, false, true, true, false, false, true, true, true, true, true, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, false,
            false, false, false, false, true, false, false, false, true, true, false, true, true,
            true, true, false,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, false,
            false, false, false, true, true, true, false, false, true, false, false, true, false,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, false, false,
            true, false, false, false, true, true, false, true, true, true, false, true, false,
            false, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            false, false, true, true, false, false, true, false, true, true, false, true, false,
            true, false,
        ],
    ],
];
