// GENERATED by tests/gen_goldens.py -- do not edit by hand.
//
// Values produced by running the real references: tools/compile_layout.py's
// packers, tools/compile_fonts.py's font builder, display.py's own CPython
// _dim_frame, and the independent `qrcode` package.
#![allow(dead_code)]

pub struct PackedCase {
    pub name: &'static str,
    pub width: usize,
    pub height: usize,
    /// Row-major palette indices that went in.
    pub indices: &'static [u8],
    /// The packed bytes that came out.
    pub packed: &'static [u8],
}

pub struct GlyphGolden {
    pub codepoint: u32,
    pub width: i32,
    pub bits: &'static [u8],
}

pub struct FontGolden {
    pub name: &'static str,
    pub height: i32,
    /// FNV-1a over every codepoint 32..=255 resolved to `(u16 width, bits)` and
    /// concatenated — the whole table, reachable through the public API.
    pub glyphs_fnv: u64,
    pub glyphs: &'static [GlyphGolden],
}

pub struct DimCase {
    /// Index into the fade ladder.
    pub step: usize,
    pub dimmed: &'static [u8],
}

/// FNV-1a, 64-bit — the digest the font goldens are recorded with.
pub fn fnv1a64(data: &[u8]) -> u64 {
    let mut value: u64 = 0xCBF2_9CE4_8422_2325;
    for byte in data {
        value = (value ^ *byte as u64).wrapping_mul(0x100_0000_01B3);
    }
    value
}

/// Index patterns packed by `tools/compile_layout.py`'s `pack_*`
/// functions — the normative definition of each format's bit order.
pub const PACKED_CASES: &[PackedCase] = &[
    PackedCase {
        name: "mono_11x3",
        width: 11,
        height: 3,
        indices: &[
            0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01,
            0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01,
            0x00, 0x01, 0x00, 0x01, 0x00,
        ],
        packed: &[0x55, 0x40, 0xaa, 0xa0, 0x55, 0x40],
    },
    PackedCase {
        name: "gs2_7x2",
        width: 7,
        height: 2,
        indices: &[
            0x00, 0x03, 0x02, 0x01, 0x00, 0x03, 0x02, 0x01, 0x00, 0x03, 0x02, 0x01, 0x00, 0x03,
        ],
        packed: &[0x6c, 0x2c, 0xb1, 0x31],
    },
    PackedCase {
        name: "gs4_5x2",
        width: 5,
        height: 2,
        indices: &[0x00, 0x05, 0x0a, 0x0f, 0x04, 0x01, 0x06, 0x0b, 0x00, 0x05],
        packed: &[0x05, 0xaf, 0x40, 0x16, 0xb0, 0x50],
    },
    PackedCase {
        name: "gs8_3x3",
        width: 3,
        height: 3,
        indices: &[0x00, 0x07, 0x0e, 0x0d, 0x14, 0x1b, 0x1a, 0x21, 0x28],
        packed: &[0x00, 0x07, 0x0e, 0x0d, 0x14, 0x1b, 0x1a, 0x21, 0x28],
    },
    PackedCase {
        name: "gs4_rows_5x2",
        width: 5,
        height: 2,
        indices: &[0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a],
        packed: &[0x12, 0x34, 0x50, 0x67, 0x89, 0xa0],
    },
    PackedCase {
        name: "gs2_leftmost",
        width: 4,
        height: 1,
        indices: &[0x01, 0x00, 0x00, 0x00],
        packed: &[0x01],
    },
    PackedCase {
        name: "gs4_leftmost",
        width: 2,
        height: 1,
        indices: &[0x0a, 0x00],
        packed: &[0xa0],
    },
];

/// A 3x2 RGB565 sprite: the packed little-endian bytes and the colors
/// they must read back as.
pub const RGB565_PACKED: &[u8] = &[
    0x00, 0xf8, 0xe0, 0x07, 0x1f, 0x00, 0xff, 0xff, 0x00, 0x00, 0xaa, 0x11,
];
pub const RGB565_COLORS: &[u16] = &[0xf800, 0x07e0, 0x001f, 0xffff, 0x0000, 0x11aa];

/// Glyph tables as `tools/compile_fonts.py` builds them, one entry per
/// font in the order `tests/fonts.rs` pairs them with.
pub const FONTS: &[FontGolden] = &[
    FontGolden {
        name: "UNSCII_8",
        height: 8,
        glyphs_fnv: 0xfd56285aafd04491,
        glyphs: &[
            GlyphGolden {
                codepoint: 32,
                width: 8,
                bits: &[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
            },
            GlyphGolden {
                codepoint: 48,
                width: 8,
                bits: &[0x3c, 0x66, 0x6e, 0x76, 0x66, 0x66, 0x3c, 0x00],
            },
            GlyphGolden {
                codepoint: 65,
                width: 8,
                bits: &[0x18, 0x3c, 0x66, 0x66, 0x7e, 0x66, 0x66, 0x00],
            },
            GlyphGolden {
                codepoint: 63,
                width: 8,
                bits: &[0x3c, 0x66, 0x06, 0x0c, 0x18, 0x00, 0x18, 0x00],
            },
            GlyphGolden {
                codepoint: 233,
                width: 8,
                bits: &[0x0e, 0x00, 0x3c, 0x66, 0x7e, 0x60, 0x3c, 0x00],
            },
            GlyphGolden {
                codepoint: 241,
                width: 8,
                bits: &[0x76, 0xdc, 0x00, 0x7c, 0x66, 0x66, 0x66, 0x00],
            },
            GlyphGolden {
                codepoint: 127,
                width: 8,
                bits: &[0x3c, 0x66, 0x06, 0x0c, 0x18, 0x00, 0x18, 0x00],
            },
            GlyphGolden {
                codepoint: 255,
                width: 8,
                bits: &[0x66, 0x00, 0x66, 0x66, 0x66, 0x3e, 0x06, 0x3c],
            },
        ],
    },
    FontGolden {
        name: "UNSCII_16",
        height: 16,
        glyphs_fnv: 0x84d0c19fe09a394f,
        glyphs: &[
            GlyphGolden {
                codepoint: 32,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 48,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x38, 0x6c, 0xc6, 0xc6, 0xce, 0xd6, 0xe6, 0xc6, 0xc6, 0x6c, 0x38,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 65,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x18, 0x3c, 0x66, 0x66, 0x66, 0x7e, 0x66, 0x66, 0x66, 0x66, 0x66,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 63,
                width: 8,
                bits: &[
                    0x00, 0x3c, 0x66, 0x66, 0x06, 0x0c, 0x18, 0x18, 0x18, 0x00, 0x00, 0x18, 0x18,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 233,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x0c, 0x18, 0x00, 0x00, 0x3c, 0x66, 0x66, 0x7e, 0x60, 0x60, 0x3c,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 241,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x76, 0xdc, 0x00, 0x00, 0x7c, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 127,
                width: 8,
                bits: &[
                    0x00, 0x3c, 0x66, 0x66, 0x06, 0x0c, 0x18, 0x18, 0x18, 0x00, 0x00, 0x18, 0x18,
                    0x00, 0x00, 0x00,
                ],
            },
            GlyphGolden {
                codepoint: 255,
                width: 8,
                bits: &[
                    0x00, 0x00, 0x66, 0x66, 0x00, 0x00, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x3e,
                    0x06, 0x06, 0x3c,
                ],
            },
        ],
    },
    FontGolden {
        name: "SPLEEN_5X8",
        height: 8,
        glyphs_fnv: 0x556f42a8c652887d,
        glyphs: &[
            GlyphGolden {
                codepoint: 32,
                width: 5,
                bits: &[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
            },
            GlyphGolden {
                codepoint: 48,
                width: 5,
                bits: &[0x00, 0x60, 0x90, 0xb0, 0xd0, 0x90, 0x60, 0x00],
            },
            GlyphGolden {
                codepoint: 65,
                width: 5,
                bits: &[0x00, 0x60, 0x90, 0x90, 0xf0, 0x90, 0x90, 0x00],
            },
            GlyphGolden {
                codepoint: 63,
                width: 5,
                bits: &[0x60, 0x90, 0x10, 0x20, 0x40, 0x00, 0x40, 0x00],
            },
            GlyphGolden {
                codepoint: 233,
                width: 5,
                bits: &[0x00, 0x00, 0x70, 0x90, 0xf0, 0x80, 0x70, 0x00],
            },
            GlyphGolden {
                codepoint: 241,
                width: 5,
                bits: &[0x00, 0x00, 0xe0, 0x90, 0x90, 0x90, 0x90, 0x00],
            },
            GlyphGolden {
                codepoint: 127,
                width: 5,
                bits: &[0x60, 0x90, 0x10, 0x20, 0x40, 0x00, 0x40, 0x00],
            },
            GlyphGolden {
                codepoint: 255,
                width: 5,
                bits: &[0x00, 0x00, 0x90, 0x90, 0x90, 0x70, 0x10, 0xe0],
            },
        ],
    },
];

/// `display._dim_frame`'s CPython branch, run over a fixed pseudorandom
/// buffer at each rung of the fade ladder.
pub const DIM_SOURCE: &[u8] = &[
    0xa1, 0x4f, 0x01, 0xfc, 0x14, 0x6c, 0xef, 0x3e, 0x53, 0x9b, 0x04, 0xa2, 0xe0, 0xff, 0x85, 0xaa,
    0x37, 0x70, 0xf5, 0xe2, 0xea, 0x90, 0x99, 0x3a, 0x59, 0xc9, 0x1e, 0xe5, 0x88, 0x1a, 0xee, 0xd1,
    0x8e, 0xe8, 0xe2, 0xd5, 0xd5, 0x86, 0xe4, 0x16, 0xcf, 0x0e, 0xac, 0x46, 0xef, 0xdc, 0x3c, 0x79,
    0xc0, 0x42, 0x45, 0x4d, 0x49, 0x59, 0xc2, 0xa2, 0xca, 0x9d, 0xaf, 0x8a, 0xac, 0xf0, 0x40, 0x0d,
];

pub const DIM_CASES: &[DimCase] = &[
    DimCase {
        step: 0,
        dimmed: &[
            0x80, 0x3e, 0x80, 0xcb, 0x91, 0x53, 0xcb, 0x25, 0xcf, 0x7a, 0xc3, 0x89, 0xa0, 0xce,
            0x23, 0x8a, 0x12, 0x58, 0x51, 0xc2, 0x88, 0x78, 0x35, 0x22, 0x15, 0xa9, 0x79, 0xc4,
            0x27, 0x0a, 0x6b, 0xb1, 0x6b, 0xc0, 0xe1, 0xb4, 0xd1, 0x75, 0xc3, 0x0d, 0xcb, 0x05,
            0xaa, 0x3d, 0x0b, 0xb4, 0xf8, 0x58, 0x40, 0x3a, 0x83, 0x3c, 0x07, 0x41, 0x41, 0x8a,
            0xe8, 0x7c, 0x2b, 0x72, 0x6a, 0xc8, 0x80, 0x04,
        ],
    },
    DimCase {
        step: 1,
        dimmed: &[
            0xa0, 0x35, 0x00, 0xb3, 0x0f, 0x4b, 0x0a, 0x25, 0x6d, 0x6a, 0x83, 0x79, 0xc0, 0xb5,
            0xe3, 0x79, 0x10, 0x50, 0x0f, 0xaa, 0x87, 0x68, 0xf2, 0x21, 0xf2, 0x90, 0xd6, 0xab,
            0xe6, 0x09, 0x4a, 0x99, 0x6a, 0xa8, 0x41, 0x9c, 0x0f, 0x65, 0x03, 0x0d, 0x0a, 0x05,
            0xe9, 0x34, 0x8a, 0x9b, 0xd5, 0x50, 0x00, 0x32, 0xe3, 0x33, 0xe6, 0x38, 0x01, 0x7a,
            0x47, 0x6c, 0xea, 0x61, 0x69, 0xb0, 0xe0, 0x03,
        ],
    },
    DimCase {
        step: 2,
        dimmed: &[
            0xa0, 0x2c, 0x80, 0x92, 0x8c, 0x3a, 0x28, 0x1c, 0x0b, 0x5a, 0x42, 0x61, 0xc0, 0x94,
            0x82, 0x61, 0x0d, 0x40, 0xac, 0x89, 0x66, 0x58, 0x8f, 0x19, 0xcf, 0x78, 0x32, 0x8b,
            0x85, 0x09, 0x08, 0x81, 0x48, 0x88, 0x81, 0x83, 0x2c, 0x54, 0x22, 0x0c, 0x28, 0x04,
            0x07, 0x2c, 0xe8, 0x82, 0xb1, 0x40, 0xa0, 0x29, 0x42, 0x2b, 0xc5, 0x30, 0xa1, 0x61,
            0x86, 0x5b, 0x88, 0x51, 0x47, 0x90, 0x40, 0x03,
        ],
    },
    DimCase {
        step: 3,
        dimmed: &[
            0xc0, 0x23, 0x00, 0x7a, 0x0a, 0x32, 0x67, 0x1b, 0xa9, 0x49, 0x02, 0x51, 0xe0, 0x7b,
            0x42, 0x51, 0x0b, 0x38, 0x6a, 0x71, 0x65, 0x48, 0x4c, 0x19, 0xac, 0x60, 0x8f, 0x72,
            0x44, 0x09, 0xe7, 0x68, 0x47, 0x70, 0xe1, 0x6a, 0x6a, 0x43, 0x62, 0x0b, 0x67, 0x03,
            0x46, 0x23, 0x67, 0x6a, 0x8e, 0x38, 0x60, 0x21, 0xa2, 0x22, 0xa4, 0x28, 0x61, 0x51,
            0xe5, 0x4a, 0x47, 0x41, 0x46, 0x78, 0xa0, 0x02,
        ],
    },
];

/// The setup QR's payload, and the symbol the `qrcode` package
/// produces for it at medium ECC in byte mode — one matrix per mask
/// pattern. See gen_goldens.py's `qr_golden` for what is pinned and why.
pub const QR_PAYLOAD: &str = "WIFI:T:nopass;S:pico-scoreboard;;";
pub const QR_VERSION: u8 = 3;
pub const QR_SIZE: i32 = 29;
pub const QR_BY_MASK: &[&[&[bool]]] = &[
    &[
        &[
            true, true, true, true, true, true, true, false, false, true, true, false, true, false,
            true, false, false, false, true, true, false, false, true, true, true, true, true,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, false, false, false, true,
            true, false, false, false, false, false, true, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, false, true,
            false, false, true, false, false, false, true, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, false, false,
            true, false, false, true, false, true, true, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, false,
            true, false, false, true, true, true, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, true, true, false,
            false, true, true, true, false, true, true, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, false, true, false, true, true, true, true, false, false, false, false,
            false, false, false, false,
        ],
        &[
            true, false, true, false, true, false, true, false, false, false, true, false, true,
            false, false, false, true, true, false, true, true, false, false, false, true, false,
            false, true, false,
        ],
        &[
            false, false, false, false, false, true, false, false, false, true, true, false, true,
            true, false, true, true, true, true, false, false, false, true, false, false, true,
            true, true, false,
        ],
        &[
            true, false, true, false, false, true, true, false, false, true, true, true, false,
            false, true, true, true, true, true, false, false, false, true, true, false, true,
            true, true, true,
        ],
        &[
            false, true, true, true, true, true, false, true, true, false, false, false, false,
            true, true, false, true, true, false, false, true, false, true, true, false, true,
            false, true, true,
        ],
        &[
            false, false, false, false, true, false, true, false, true, false, false, false, true,
            false, true, true, true, true, false, true, true, false, true, true, false, true,
            false, true, true,
        ],
        &[
            false, true, false, true, true, true, false, true, true, true, true, false, true,
            false, true, true, false, true, false, false, true, false, true, false, false, true,
            true, true, false,
        ],
        &[
            true, false, true, false, false, true, true, true, true, true, true, false, true, true,
            false, false, false, false, false, false, false, false, false, true, true, false,
            false, true, true,
        ],
        &[
            false, false, false, true, true, true, false, false, false, true, false, true, true,
            false, false, false, false, true, true, false, false, false, true, true, false, false,
            false, false, false,
        ],
        &[
            true, true, true, true, true, false, true, false, true, true, false, false, false,
            false, false, true, false, true, false, false, true, true, true, false, false, true,
            true, false, false,
        ],
        &[
            false, true, false, true, false, true, false, true, false, true, false, false, true,
            true, false, false, false, true, false, false, true, false, false, false, false, false,
            false, true, false,
        ],
        &[
            true, false, false, true, true, false, true, true, true, false, false, true, true,
            false, true, false, false, true, true, false, false, false, true, false, true, false,
            true, true, true,
        ],
        &[
            false, true, true, true, true, true, false, true, false, true, true, false, true, true,
            true, false, false, true, false, true, false, false, true, true, false, true, false,
            false, true,
        ],
        &[
            true, false, true, true, true, true, true, true, false, false, true, false, false,
            false, true, true, false, true, false, true, true, true, true, true, true, true, false,
            true, true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, true, false, false,
            false, true, false, false, false, false, true, true, false, false, false, true, true,
            true, false, false,
        ],
        &[
            true, true, true, true, true, true, true, false, false, true, false, false, true, true,
            false, false, true, true, false, true, true, false, true, false, true, false, false,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, false, true, true,
            false, false, true, true, true, true, false, true, false, false, false, true, false,
            false, false, false,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, true, false, true,
            false, false, false, true, true, false, false, true, true, true, true, true, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, false, false,
            true, false, false, true, true, false, true, false, true, false, false, true, false,
            true, true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, true, false, false,
            false, true, false, true, false, true, false, true, true, false, true, true, false,
            false, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, false, false,
            true, false, false, false, true, true, false, true, true, true, false, true, false,
            false, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, false, false, true, true,
            false, false, false, true, false, true, true, false, false, true, false, false, false,
            true, true,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, true, false, true, true, true, true,
            true, true, false, true, true, false, false, false, true, true, true, true, true, true,
            true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            false, false, true, false, true, false, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, true, true,
            false, false, false, true, false, false, true, false, true, false, true, true, true,
            false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, false,
            false, false, true, true, true, true, false, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, false, false,
            false, false, true, true, false, true, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, false, true, false, false,
            true, true, false, true, true, true, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, false, false, false, false,
            false, true, false, false, false, false, true, false, true, false, false, false, false,
            false, false, false, false,
        ],
        &[
            true, false, true, false, false, false, true, true, false, true, true, true, true,
            true, false, true, true, false, false, false, true, false, false, true, false, false,
            true, false, true,
        ],
        &[
            false, true, false, true, false, false, false, true, false, false, true, true, true,
            false, false, false, true, false, true, true, false, true, true, true, false, false,
            true, false, false,
        ],
        &[
            true, true, true, true, false, false, true, true, false, false, true, false, false,
            true, true, false, true, false, true, true, false, true, true, false, false, false,
            true, false, true,
        ],
        &[
            false, false, true, false, true, false, false, false, true, true, false, true, false,
            false, true, true, true, false, false, true, true, true, true, false, false, false,
            false, false, true,
        ],
        &[
            false, true, false, true, true, true, true, true, true, true, false, true, true, true,
            true, false, true, false, false, false, true, true, true, false, false, false, false,
            false, true,
        ],
        &[
            false, false, false, false, true, false, false, false, true, false, true, true, true,
            true, true, false, false, false, false, true, true, true, true, true, false, false,
            true, false, false,
        ],
        &[
            true, true, true, true, false, false, true, false, true, false, true, true, true,
            false, false, true, false, true, false, true, false, true, false, false, true, true,
            false, false, true,
        ],
        &[
            false, true, false, false, true, false, false, true, false, false, false, false, true,
            true, false, true, false, false, true, true, false, true, true, false, false, true,
            false, true, false,
        ],
        &[
            true, false, true, false, true, true, true, true, true, false, false, true, false,
            true, false, false, false, false, false, true, true, false, true, true, false, false,
            true, true, false,
        ],
        &[
            false, false, false, false, false, false, false, false, false, false, false, true,
            true, false, false, true, false, false, false, true, true, true, false, true, false,
            true, false, false, false,
        ],
        &[
            true, true, false, false, true, true, true, false, true, true, false, false, true,
            true, true, true, false, false, true, true, false, true, true, true, true, true, true,
            false, true,
        ],
        &[
            false, false, true, false, true, false, false, false, false, false, true, true, true,
            false, true, true, false, false, false, false, false, true, true, false, false, false,
            false, true, true,
        ],
        &[
            true, true, true, false, true, false, true, false, false, true, true, true, false,
            true, true, false, false, false, false, false, true, true, true, true, true, false,
            false, false, true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, true, true, false,
            true, true, true, false, true, false, false, true, false, false, false, true, false,
            true, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, false, true, true, false,
            false, true, true, false, false, false, true, false, true, false, true, true, false,
            false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, false, true,
            true, false, false, true, false, true, true, true, false, false, false, true, true,
            false, true, false,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, true, true,
            true, false, true, true, false, false, true, true, true, true, true, true, true, false,
            true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, false,
            false, false, true, true, false, false, false, false, false, false, true, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, true, true, true, false, false, false, true, true, false,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, true, true, false,
            false, false, true, false, false, true, true, true, false, true, true, true, true,
            false, false, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, true, false, true, true, false,
            false, true, false, false, false, false, true, true, false, false, false, true, false,
            false, true,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, false, false, false, false, true,
            false, false, true, true, false, true, true, true, false, true, true, true, true, true,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, false, true, false,
            false, false, false, false, true, true, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, true,
            false, true, false, true, false, false, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, true,
            false, false, false, true, true, false, false, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, false, true, false,
            true, true, true, false, true, true, true, true, false, true, false, true, true, true,
            false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, true, false, true,
            true, true, true, true, true, false, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, false, false, true,
            true, false, true, false, false, false, false, true, false, false, false, false, false,
            false, false, false,
        ],
        &[
            true, false, true, true, true, true, true, false, false, true, false, false, true,
            false, true, true, false, true, false, true, false, false, true, true, true, true,
            true, false, false,
        ],
        &[
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            false, false, true, true, false, false, true, false, false, true, true, true, false,
            true, true, false,
        ],
        &[
            true, false, false, true, true, true, true, false, true, false, false, true, false,
            false, false, false, false, true, true, false, true, true, false, true, false, true,
            false, false, false,
        ],
        &[
            true, false, true, true, true, false, false, false, true, false, false, true, true,
            false, true, false, true, false, true, true, true, false, true, false, true, false,
            false, true, true,
        ],
        &[
            false, false, true, true, false, false, true, false, false, true, true, false, true,
            false, false, false, false, true, false, true, false, true, false, true, false, true,
            true, false, false,
        ],
        &[
            true, false, false, true, true, false, false, false, true, true, true, true, false,
            true, true, true, false, false, true, true, true, false, true, true, true, false, true,
            true, false,
        ],
        &[
            true, false, false, true, true, true, true, true, false, false, false, false, true,
            true, true, true, true, false, false, false, true, true, true, true, true, false, true,
            false, false,
        ],
        &[
            true, true, false, true, true, false, false, true, false, true, false, false, false,
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            false, false, false,
        ],
        &[
            true, true, false, false, false, false, true, false, false, false, true, false, false,
            false, true, false, true, true, false, false, false, false, false, false, false, true,
            false, true, true,
        ],
        &[
            true, false, false, true, false, false, false, false, false, true, false, true, false,
            false, false, false, false, false, true, true, true, false, false, true, true, true,
            false, true, false,
        ],
        &[
            true, false, true, false, false, false, true, true, false, true, true, true, true,
            false, false, true, true, true, true, false, true, true, false, false, true, false,
            false, false, false,
        ],
        &[
            true, false, true, true, true, false, false, false, false, true, true, true, false,
            false, true, false, false, false, true, false, false, false, true, false, true, false,
            false, false, true,
        ],
        &[
            true, false, false, false, false, true, true, true, true, true, false, false, false,
            false, false, false, true, true, false, true, true, true, true, true, true, true, true,
            false, false,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, true, true, true,
            true, true, false, false, true, true, false, true, false, false, false, true, false,
            true, false, false,
        ],
        &[
            true, true, true, true, true, true, true, false, false, false, true, false, true, true,
            true, true, false, true, false, true, true, false, true, false, true, false, true,
            false, false,
        ],
        &[
            true, false, false, false, false, false, true, false, true, false, false, false, false,
            true, false, true, true, false, false, true, true, false, false, false, true, true,
            false, false, false,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, true,
            false, true, true, false, true, false, false, true, true, true, true, true, false,
            true, true, false,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, true,
            false, false, false, true, false, true, false, false, true, false, true, false, true,
            true, true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, false,
            false, false, true, false, false, true, false, false, false, true, true, true, false,
            true, true, false,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, true, true,
            false, false, false, false, false, false, true, true, true, true, true, false, true,
            false, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, true, true, false, true, true,
            true, true, true, true, false, true, false, true, true, true, false, false, true,
            false, false,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, true, false, false, false, true,
            false, false, true, true, false, true, true, true, false, true, true, true, true, true,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, false, false, true,
            false, true, true, false, false, false, false, false, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, false, false,
            true, true, true, false, false, true, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, true,
            false, false, false, true, true, false, false, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, false, false, true,
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, false, false,
            false, false, true, false, false, true, true, true, true, false, true, false, false,
            false, false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, false, true,
            false, true, true, false, false, true, true, false, false, false, false, false, false,
            false, false, false, false,
        ],
        &[
            true, false, true, true, false, true, true, true, false, false, true, false, false,
            true, true, false, true, true, true, false, false, false, true, false, false, true,
            false, true, true,
        ],
        &[
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            false, false, true, true, false, false, true, false, false, true, true, true, false,
            true, true, false,
        ],
        &[
            false, false, true, false, true, false, true, false, false, true, false, false, true,
            false, true, true, false, false, false, false, false, false, false, false, true, true,
            true, true, false,
        ],
        &[
            false, true, true, false, false, false, false, true, true, true, true, true, false,
            true, true, true, false, false, false, false, true, true, false, false, false, true,
            false, false, false,
        ],
        &[
            false, false, true, true, false, false, true, false, false, true, true, false, true,
            false, false, false, false, true, false, true, false, true, false, true, false, true,
            true, false, false,
        ],
        &[
            false, false, true, false, true, true, false, false, false, false, true, false, true,
            true, false, false, false, true, false, true, false, true, true, false, false, false,
            false, false, false,
        ],
        &[
            false, true, false, false, false, true, true, false, false, true, true, false, false,
            false, true, false, false, false, true, true, true, false, false, true, false, true,
            true, true, true,
        ],
        &[
            true, true, false, true, true, false, false, true, false, true, false, false, false,
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            false, false, false,
        ],
        &[
            false, true, true, true, false, true, true, false, true, true, true, true, true, false,
            false, true, true, false, true, false, true, true, false, true, true, true, true,
            false, true,
        ],
        &[
            false, true, false, false, true, false, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, true, true, true, true, false, false,
            false, false, true,
        ],
        &[
            true, false, true, false, false, false, true, true, false, true, true, true, true,
            false, false, true, true, true, true, false, true, true, false, false, true, false,
            false, false, false,
        ],
        &[
            false, false, false, false, true, true, false, false, true, false, true, false, true,
            false, false, true, false, true, false, false, true, true, true, true, false, false,
            true, true, true,
        ],
        &[
            false, true, false, true, true, true, true, false, true, false, true, false, true,
            true, false, true, false, true, true, false, true, true, true, true, true, false, true,
            true, true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, true, true, true,
            true, true, false, false, true, true, false, true, false, false, false, true, false,
            true, false, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, true, true, true, false, true,
            false, false, false, false, true, true, true, false, true, false, true, false, false,
            true, false,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, true, false, true,
            false, false, false, false, false, true, false, true, false, false, false, true, false,
            false, true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, false, false, true,
            false, true, true, false, true, false, false, true, true, true, true, true, false,
            true, true, false,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, true, false, false,
            false, true, true, true, true, false, false, true, false, false, false, true, true,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, true, false, true, true,
            false, false, true, false, false, true, false, true, false, true, false, true, true,
            false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, true, true,
            false, false, false, false, false, false, true, true, true, true, true, false, true,
            false, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, true, false, true,
            false, false, true, false, true, true, true, false, true, false, true, false, false,
            true, false,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, true, true, false, false, true, true,
            true, false, true, false, true, false, false, false, true, true, true, true, true,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, true, false,
            true, true, true, false, true, true, true, false, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, true, false,
            false, true, false, false, true, true, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, false,
            false, false, false, false, false, true, false, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, true, false,
            false, false, false, false, true, true, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, false, true, false, true,
            false, false, false, true, true, false, true, false, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, true, true, false,
            true, false, true, true, true, true, false, true, false, false, false, false, false,
            false, false, false,
        ],
        &[
            true, false, false, false, true, false, true, true, true, false, false, false, true,
            true, false, false, false, true, false, false, true, true, true, true, true, true,
            false, false, true,
        ],
        &[
            true, false, true, true, false, false, false, false, true, false, true, true, false,
            true, true, false, true, false, false, false, true, true, true, true, true, true,
            false, false, false,
        ],
        &[
            false, false, false, true, false, false, true, false, true, false, true, false, true,
            false, false, false, true, false, false, false, true, true, true, false, true, true,
            false, false, true,
        ],
        &[
            false, false, true, true, false, true, false, false, true, false, true, false, false,
            false, true, false, false, true, false, true, true, false, false, true, false, false,
            false, true, false,
        ],
        &[
            false, true, false, false, false, false, true, true, true, false, true, false, true,
            true, true, true, false, true, false, false, true, false, false, true, false, false,
            false, true, false,
        ],
        &[
            true, true, true, false, true, false, false, true, false, false, true, true, false,
            false, false, false, false, false, true, false, false, true, true, true, true, true,
            false, false, false,
        ],
        &[
            false, false, false, true, false, false, true, true, false, false, true, true, false,
            true, true, true, false, true, true, false, true, true, false, false, false, false,
            true, false, true,
        ],
        &[
            false, true, false, true, false, true, false, true, false, true, true, true, true,
            true, false, false, true, true, true, true, false, false, false, true, false, true,
            false, false, true,
        ],
        &[
            true, false, true, true, false, false, true, true, true, true, true, false, false,
            true, false, true, true, true, false, true, true, true, false, false, false, false,
            true, false, true,
        ],
        &[
            true, true, true, false, false, false, false, true, true, false, false, true, false,
            true, true, true, false, false, true, false, false, true, false, true, true, false,
            true, false, false,
        ],
        &[
            false, false, true, false, true, true, true, true, false, true, false, false, false,
            false, false, true, false, false, false, false, true, true, true, true, false, false,
            false, false, true,
        ],
        &[
            false, false, true, true, false, true, false, false, false, true, false, false, true,
            false, true, false, true, true, false, false, false, false, false, true, false, false,
            false, false, false,
        ],
        &[
            true, true, true, true, false, true, true, false, false, false, false, false, false,
            true, true, true, true, true, false, false, true, true, true, true, true, false, false,
            true, false,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, true, true, true,
            false, false, true, false, true, true, true, true, false, false, false, true, true,
            false, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, false, true, false, true,
            true, true, true, false, true, true, true, false, true, false, true, false, true,
            false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, true, true,
            true, false, true, false, true, true, true, true, false, false, false, true, true,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, false, false, true,
            true, false, false, false, true, false, true, true, true, true, true, true, true,
            false, false, false,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, true, true,
            true, true, true, false, true, true, true, false, false, true, false, false, false,
            false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, true, true,
            false, false, true, true, true, false, false, false, false, false, false, false, false,
            true, true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, false, false,
            false, false, false, false, true, true, true, true, true, true, false, false, true,
            true, false, true, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            false, false, true, true, false, false, true, false, true, true, false, true, false,
            true, false,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, false, false, true, true, true, true,
            true, true, false, true, true, false, false, false, true, true, true, true, true, true,
            true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, false, true, false,
            false, false, true, false, true, true, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, true,
            false, true, false, true, false, false, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, false, true, true,
            false, true, true, false, true, false, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, false, true, false,
            true, true, true, false, true, true, true, true, false, true, false, true, true, true,
            false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, false, true,
            true, true, false, true, true, false, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, false, false,
            true, true, false, false, false, false, false, false, true, false, false, false, false,
            false, false, false, false,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, false, false, true,
            false, true, true, false, true, false, true, false, true, true, false, false, true,
            true, true, false,
        ],
        &[
            true, true, true, true, true, false, false, true, true, false, false, true, false,
            false, true, false, false, false, false, true, true, true, false, true, true, false,
            false, false, true,
        ],
        &[
            true, false, false, true, true, true, true, false, true, false, false, true, false,
            false, false, false, false, true, true, false, true, true, false, true, false, true,
            false, false, false,
        ],
        &[
            true, false, true, false, true, false, false, false, true, true, false, true, true,
            false, true, true, true, false, true, true, true, true, true, false, true, false,
            false, false, true,
        ],
        &[
            false, true, false, true, true, true, true, true, true, true, false, true, true, true,
            true, false, true, false, false, false, true, true, true, false, false, false, false,
            false, true,
        ],
        &[
            true, false, false, false, true, false, false, false, true, false, true, true, false,
            true, true, false, false, false, true, true, true, true, true, true, true, false, true,
            false, false,
        ],
        &[
            true, false, false, true, true, true, true, true, false, false, false, false, true,
            true, true, true, true, false, false, false, true, true, true, true, true, false, true,
            false, false,
        ],
        &[
            true, true, true, false, false, false, false, true, true, false, true, false, false,
            true, true, true, true, false, false, true, true, true, false, false, true, true, true,
            true, true,
        ],
        &[
            true, true, false, false, false, false, true, false, false, false, true, false, false,
            false, true, false, true, true, false, false, false, false, false, false, false, true,
            false, true, true,
        ],
        &[
            true, false, false, false, false, false, false, false, false, false, false, true,
            false, false, false, true, false, false, true, true, true, true, false, true, true,
            true, false, false, false,
        ],
        &[
            true, true, false, false, true, true, true, false, true, true, false, false, true,
            true, true, true, false, false, true, true, false, true, true, true, true, true, true,
            false, true,
        ],
        &[
            true, false, true, false, true, false, false, false, false, false, true, true, false,
            false, true, true, false, false, true, false, false, true, true, false, true, false,
            false, true, true,
        ],
        &[
            true, false, false, false, false, true, true, true, true, true, false, false, false,
            false, false, false, true, true, false, true, true, true, true, true, true, true, true,
            false, false,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, false, true, true,
            true, false, true, true, true, true, false, true, false, false, false, true, false,
            false, true, true,
        ],
        &[
            true, true, true, true, true, true, true, false, false, false, true, false, true, true,
            true, true, false, true, false, true, true, false, true, false, true, false, true,
            false, false,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, false, false,
            true, false, false, true, false, false, true, true, false, false, false, true, true,
            false, true, false,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, true, true,
            true, false, true, true, false, false, true, true, true, true, true, true, true, false,
            true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, true,
            false, false, true, true, false, true, false, false, false, false, true, false, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, false, false, false,
            false, false, true, false, false, true, false, false, false, true, true, true, false,
            true, true, false,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            false, true, true, true, false, false, true, false, false, false, true, false, true,
            true, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, true, true, false, true, true,
            true, true, true, true, false, true, false, true, true, true, false, false, true,
            false, false,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, true, false, true, true, true, true,
            true, true, false, true, true, false, false, false, true, true, true, true, true, true,
            true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, false, true, false,
            true, true, true, false, true, true, true, false, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, false, true,
            true, true, false, false, false, false, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, false, true, true,
            false, true, true, false, true, false, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, false, false, false,
            true, false, true, false, false, true, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, false, true, true,
            true, true, false, false, false, false, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, false, false, false, false,
            true, false, true, false, false, false, false, true, false, false, false, false, false,
            false, false, false, false,
        ],
        &[
            true, false, false, true, true, true, true, true, true, true, true, false, true, true,
            true, true, true, true, false, false, false, true, false, false, true, false, true,
            true, true,
        ],
        &[
            true, true, true, true, true, false, false, true, true, false, false, true, false,
            false, true, false, false, false, false, true, true, true, false, true, true, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, false, false, false,
            false, true, false, false, false, true, false, false, true, false, false, false, true,
            true, false, false,
        ],
        &[
            true, false, true, false, false, true, false, false, true, true, true, false, true,
            false, true, true, false, true, true, true, true, true, false, true, true, false,
            false, false, false,
        ],
        &[
            false, true, false, true, true, true, true, true, true, true, false, true, true, true,
            true, false, true, false, false, false, true, true, true, false, false, false, false,
            false, true,
        ],
        &[
            true, true, true, false, true, false, false, true, false, false, true, true, false,
            false, false, false, false, false, true, false, false, true, true, true, true, true,
            false, false, false,
        ],
        &[
            true, true, false, true, false, true, true, false, false, false, true, false, true,
            false, true, true, false, false, false, true, true, true, false, true, true, true,
            true, false, true,
        ],
        &[
            true, true, true, false, false, false, false, true, true, false, true, false, false,
            true, true, true, true, false, false, true, true, true, false, false, true, true, true,
            true, true,
        ],
        &[
            true, true, true, false, false, true, true, false, true, false, true, true, false,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            true, true, true,
        ],
        &[
            true, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, true, true, true, true, true, true, true, true, false, true, true, false,
            false, true,
        ],
        &[
            true, true, false, false, true, true, true, false, true, true, false, false, true,
            true, true, true, false, false, true, true, false, true, true, true, true, true, true,
            false, true,
        ],
        &[
            true, true, false, false, true, false, false, true, true, false, true, true, false,
            true, false, true, false, false, true, true, true, true, true, false, true, true, true,
            true, true,
        ],
        &[
            true, true, false, false, true, true, true, false, true, true, true, false, false,
            true, false, false, false, true, false, false, true, true, true, true, true, false,
            true, false, true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, false, false, true, true,
            true, false, true, true, true, true, false, true, false, false, false, true, false,
            false, true, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, true, true, true,
            false, true, false, false, false, true, true, false, true, false, true, false, false,
            false, false,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, true, true, false,
            true, false, false, false, true, false, true, true, false, false, false, true, true,
            false, true, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, true, true, true, true,
            false, true, true, false, false, true, true, true, true, true, true, true, false, true,
            true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, true, true, true, true, true,
            true, true, true, false, true, true, true, false, false, true, false, false, false,
            false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, false, false,
            true, false, true, true, false, true, true, false, false, false, true, true, true,
            true, true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, true, false, true, true,
            false, true, true, true, false, false, true, false, false, false, true, false, true,
            true, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, true, true, true, true, true,
            false, true, true, false, false, true, true, true, true, false, false, false, false,
            false, false,
        ],
    ],
    &[
        &[
            true, true, true, true, true, true, true, false, false, true, true, false, true, false,
            true, false, false, false, true, true, false, false, true, true, true, true, true,
            true, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, false, true,
            false, false, false, true, false, false, false, true, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, true,
            false, true, true, false, true, false, true, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, true, false, false,
            true, false, false, true, false, true, true, true, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, false, false, false, true, false,
            false, false, false, false, true, true, false, false, false, true, false, true, true,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, true, true, true, false, false,
            false, false, true, true, true, true, true, false, false, true, false, false, false,
            false, false, true,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            true, false, true, false, true, false, true, false, true, true, true, true, true, true,
            true,
        ],
        &[
            false, false, false, false, false, false, false, false, false, true, true, true, false,
            true, false, true, true, true, true, false, true, false, false, false, false, false,
            false, false, false,
        ],
        &[
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            false, true, false, true, false, false, true, false, true, false, true, false, false,
            false, false, false,
        ],
        &[
            false, false, false, false, false, true, false, false, false, true, true, false, true,
            true, false, true, true, true, true, false, false, false, true, false, false, true,
            true, true, false,
        ],
        &[
            true, true, true, false, true, true, true, true, false, true, false, true, false, true,
            true, true, false, true, true, true, false, false, false, true, false, false, true,
            true, false,
        ],
        &[
            false, true, false, true, true, false, false, true, false, false, false, true, false,
            true, false, false, true, false, false, false, false, false, true, false, false, true,
            true, true, true,
        ],
        &[
            false, false, false, false, true, false, true, false, true, false, false, false, true,
            false, true, true, true, true, false, true, true, false, true, true, false, true,
            false, true, true,
        ],
        &[
            false, false, false, true, false, true, false, false, true, true, false, false, true,
            true, true, true, true, true, false, true, true, false, false, false, false, false,
            true, true, true,
        ],
        &[
            true, false, false, false, false, false, true, true, false, true, true, true, true,
            true, true, false, false, true, false, false, true, false, false, false, true, false,
            true, true, true,
        ],
        &[
            false, false, false, true, true, true, false, false, false, true, false, true, true,
            false, false, false, false, true, true, false, false, false, true, true, false, false,
            false, false, false,
        ],
        &[
            true, false, true, true, false, false, true, true, true, true, true, false, false,
            true, false, true, true, true, false, true, true, true, false, false, false, false,
            true, false, true,
        ],
        &[
            false, true, true, true, false, false, false, true, true, true, false, true, true,
            true, true, false, false, false, false, false, false, false, false, true, false, false,
            true, true, false,
        ],
        &[
            true, false, false, true, true, false, true, true, true, false, false, true, true,
            false, true, false, false, true, true, false, false, false, true, false, true, false,
            true, true, true,
        ],
        &[
            false, false, true, true, false, true, false, false, false, true, false, false, true,
            false, true, false, true, true, false, false, false, false, false, true, false, false,
            false, false, false,
        ],
        &[
            true, false, false, true, true, false, true, true, true, false, true, true, false,
            false, false, true, false, false, false, true, true, true, true, true, true, true,
            true, true, true,
        ],
        &[
            false, false, false, false, false, false, false, false, true, true, true, false, false,
            false, true, false, false, false, false, true, true, false, false, false, true, true,
            true, false, false,
        ],
        &[
            true, true, true, true, true, true, true, false, false, true, true, false, true, false,
            false, false, false, true, false, false, true, false, true, false, true, true, false,
            true, false,
        ],
        &[
            true, false, false, false, false, false, true, false, true, false, false, false, true,
            false, true, true, true, false, true, false, true, false, false, false, true, false,
            true, false, false,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, false, true,
            false, false, false, true, true, false, false, true, true, true, true, true, false,
            false, false, true,
        ],
        &[
            true, false, true, true, true, false, true, false, true, false, false, false, false,
            false, false, false, false, true, false, false, false, true, true, false, true, true,
            true, true, false,
        ],
        &[
            true, false, true, true, true, false, true, false, false, true, true, true, false,
            false, false, false, true, true, true, false, false, true, false, false, true, false,
            true, false, true,
        ],
        &[
            true, false, false, false, false, false, true, false, false, false, true, false, false,
            true, false, false, false, true, true, false, true, true, true, false, true, false,
            false, true, false,
        ],
        &[
            true, true, true, true, true, true, true, false, true, false, true, false, true, false,
            false, false, true, true, false, false, true, false, true, true, false, true, false,
            true, false,
        ],
    ],
];
