#!/usr/bin/env python3
"""Compile font source files into MicroPython glyph-table modules.

Reads fonts from `firmware/assets/fonts/` and writes generated `.py` modules
to `firmware/src/scoreboard/fonts/`. The output directory is partly generated
(individual font modules) and partly hand-written (`__init__.py` has the
FontWriter class and helpers). Only the individual font modules are gitignored.

Uses the vendored font_to_py (tools/vendor/font_to_py.py, freetype-based) as
a library for glyph rendering and data packing: its `Font.build_arrays()`
produces the same `_font`/`_index` blobs its CLI always has. The emitted
module format is our own, though — instead of an allocating `get_ch()`
function, each module builds a glyph table once at import: `GLYPHS[cp - 32]`
is a ready-to-blit `(memoryview, width, HEIGHT, framebuf.MONO_HLSB)` tuple,
so text rendering on Core 1 never allocates (see scoreboard.fonts.FontWriter).
"""

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
ASSETS_DIR = REPO_ROOT / "firmware" / "assets" / "fonts"
OUTPUT_DIR = REPO_ROOT / "firmware" / "src" / "scoreboard" / "fonts"
VENDOR_DIR = SCRIPT_DIR / "vendor"

sys.path.insert(0, str(VENDOR_DIR))
import font_to_py  # noqa: E402
import freetype  # noqa: E402  (font_to_py's own dependency)

# Character range and default glyph, matching font_to_py's CLI defaults
# (`-s 32 -l 126 -e 63`): printable ASCII with '?' as the fallback glyph.
MINCHAR = 32
MAXCHAR = 126
DEFCHAR = ord("?")
CHAR_COUNT = MAXCHAR - MINCHAR + 1  # 95

# (source-filename-in-assets, expected height, output-module-filename)
# Bitmapped fonts (.pcf/.bdf) carry their own size; the height here is an
# assertion against the embedded value, not an input.
FONTS = [
    ("unscii_8.pcf",   8,  "unscii_8.py"),
    ("unscii_16.pcf", 16,  "unscii_16.py"),
    ("spleen-5x8.bdf", 8,  "spleen_5x8.py"),
]

MODULE_TEMPLATE = '''\
"""Generated by tools/compile_fonts.py from {src_name} — do not edit.

{height}px glyph table, printable ASCII 32..126, framebuf.MONO_HLSB packed
(rows byte-padded, MSB = leftmost pixel). `GLYPHS[codepoint - 32]` is a
ready-to-blit `(memoryview, width, HEIGHT, framebuf.MONO_HLSB)` tuple;
`DEFAULT` is the fallback glyph ('?') for out-of-range codepoints. The table
is built once at import (on Core 0), so rendering via
scoreboard.fonts.FontWriter never allocates on the display thread.
"""
import framebuf

HEIGHT = {height}

# Per-glyph records: u16-LE width prefix + bitmap rows. Entry offsets live in
# _index (u16-LE each): [0] = default glyph, [1..{char_count}] = chars
# {minchar}..{maxchar}; absent glyphs point at offset 0 (the default glyph).
{font_literal}

{index_literal}

_mv = memoryview(_font)


def _entry(i):
    o = _index[2 * i] | (_index[2 * i + 1] << 8)
    w = _font[o] | (_font[o + 1] << 8)
    return (_mv[o + 2:o + 2 + ((w - 1) // 8 + 1) * HEIGHT], w, HEIGHT,
            framebuf.MONO_HLSB)


DEFAULT = _entry(0)
GLYPHS = tuple(_entry(i) for i in range(1, {char_count} + 1))
del _entry
'''


def bytes_literal(name: str, blob: bytes, per_line: int = 16) -> str:
    """Emit `name = (b'...' b'...')` with fixed-width hex escapes."""
    lines = [f"{name} = ("]
    for i in range(0, len(blob), per_line):
        chunk = blob[i:i + per_line]
        lines.append("    b'" + "".join(f"\\x{b:02x}" for b in chunk) + "'")
    lines.append(")")
    return "\n".join(lines)


def build_blobs(src: Path, expected_height: int) -> tuple[bytes, bytes]:
    """Render one font via font_to_py and return its (_font, _index) blobs."""
    # Bitmapped fonts define their own pixel size; mirror font_to_py's CLI,
    # which ignores the height argument and reads the embedded size.
    face = freetype.Face(str(src))
    size = face._get_available_sizes()[0].height

    fnt = font_to_py.Font(
        str(src), size, MINCHAR, MAXCHAR,
        monospaced=False, defchar=DEFCHAR, charset="", bitmapped=True,
    )
    if fnt.height != expected_height:
        raise SystemExit(
            f"{src.name}: rendered height {fnt.height} != expected {expected_height}"
        )

    data, index, sparse = fnt.build_arrays(hmap=True, reverse=False)
    if sparse:
        raise SystemExit(f"{src.name}: unexpected sparse index for ASCII charset")
    # Sanity: default + CHAR_COUNT chars + end sentinel.
    assert len(index) == (CHAR_COUNT + 2) * 2, len(index)
    return bytes(data), bytes(index)


def compile_all() -> None:
    if not ASSETS_DIR.is_dir():
        raise SystemExit(f"Error: assets directory not found: {ASSETS_DIR}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for src_name, height, out_name in FONTS:
        src = ASSETS_DIR / src_name
        if not src.is_file():
            raise SystemExit(f"Error: missing font source {src}")

        font_blob, index_blob = build_blobs(src, height)
        module = MODULE_TEMPLATE.format(
            src_name=src_name,
            height=height,
            char_count=CHAR_COUNT,
            minchar=MINCHAR,
            maxchar=MAXCHAR,
            font_literal=bytes_literal("_font", font_blob),
            index_literal=bytes_literal("_index", index_blob),
        )
        out = OUTPUT_DIR / out_name
        out.write_text(module, encoding="utf-8", newline="\n")
        print(f"[{out_name}] {src_name}: {len(font_blob)} B data, "
              f"{CHAR_COUNT + 1} glyph entries, height {height}")

    print(f"\nDone: {len(FONTS)} font(s) written to "
          f"{OUTPUT_DIR.relative_to(REPO_ROOT).as_posix()}/")


def main():
    compile_all()


if __name__ == "__main__":
    main()
