#!/usr/bin/env python3
"""Compile font source files into MicroPython glyph-table modules.

Reads fonts from `firmware/assets/fonts/` and writes generated `.py` modules
to `firmware/src/scoreboard/fonts/`. The output directory is partly generated
(individual font modules) and partly hand-written (`__init__.py` has the
FontWriter class and helpers). Only the individual font modules are gitignored.

Uses the vendored font_to_py (tools/vendor/font_to_py.py, freetype-based) as
a library for glyph rendering and data packing (its `Font` dict + record
layout). The emitted module format is our own, though — instead of an
allocating `get_ch()` function, each module builds a glyph table once at
import: `GLYPHS[cp - 32]` is a ready-to-blit
`(memoryview, width, HEIGHT, framebuf.MONO_HLSB)` tuple, so text rendering
on Core 1 never allocates (see scoreboard.fonts.FontWriter).
"""

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
ASSETS_DIR = REPO_ROOT / "firmware" / "assets" / "fonts"
OUTPUT_DIR = REPO_ROOT / "firmware" / "src" / "scoreboard" / "fonts"
VENDOR_DIR = SCRIPT_DIR / "vendor"

sys.path.insert(0, str(VENDOR_DIR))
import font_to_py  # noqa: E402
import freetype  # noqa: E402  (font_to_py's own dependency)

# Dense table over printable ASCII + Latin-1 (accented player names — Suárez,
# Peña — render natively; scoreboard.textfold maps anything above 0xFF down
# into this repertoire at ingest). The C1 control gap 0x7F..0x9F stays in the
# table so lookup remains a flat `cp - 32`; those entries — and any codepoint
# the source font lacks — carry the ABSENT sentinel and resolve to the
# default glyph ('?') at import.
MINCHAR = 32
MAXCHAR = 0xFF
DEFCHAR = ord("?")
CHAR_COUNT = MAXCHAR - MINCHAR + 1  # 224
_CONTROL_GAP = range(0x7F, 0xA0)
ABSENT = 0xFFFF  # index sentinel: no glyph, use DEFAULT

# Legitimately-empty bitmaps; every other blank glyph is a placeholder.
_ALLOWED_BLANK = {0x20, 0xA0}  # space, no-break space

# ASCII stand-ins consulted ONLY for codepoints whose glyph in the source
# font is a blank placeholder (spleen-5x8 ships empty bitmaps for nearly all
# of Latin-1; unscii draws the real thing and never touches this table). The
# entry reuses the stand-in's record, so e.g. 'é' renders as 'e' in spleen
# while staying a true 'é' in unscii. Codepoints absent here (currency,
# legal marks, fractions...) fall back to the '?' default.
_BLANK_STAND_IN = {
    "À": "A", "Á": "A", "Â": "A", "Ã": "A", "Ä": "A", "Å": "A", "Æ": "A",
    "Ç": "C", "È": "E", "É": "E", "Ê": "E", "Ë": "E",
    "Ì": "I", "Í": "I", "Î": "I", "Ï": "I", "Ð": "D", "Ñ": "N",
    "Ò": "O", "Ó": "O", "Ô": "O", "Õ": "O", "Ö": "O", "Ø": "O",
    "Ù": "U", "Ú": "U", "Û": "U", "Ü": "U", "Ý": "Y", "Þ": "P", "ß": "s",
    "à": "a", "á": "a", "â": "a", "ã": "a", "ä": "a", "å": "a", "æ": "a",
    "ç": "c", "è": "e", "é": "e", "ê": "e", "ë": "e",
    "ì": "i", "í": "i", "î": "i", "ï": "i", "ð": "d", "ñ": "n",
    "ò": "o", "ó": "o", "ô": "o", "õ": "o", "ö": "o", "ø": "o",
    "ù": "u", "ú": "u", "û": "u", "ü": "u", "ý": "y", "þ": "p", "ÿ": "y",
    "¡": "!", "¿": "?", "ª": "a", "º": "o", "´": "'", "¨": '"', "µ": "u",
    "·": ".", "«": '"', "»": '"', "¦": "|", "¬": "-", "¯": "-", "\xad": "-",
    "±": "+", "×": "x", "÷": "/", "¢": "c", "¹": "1", "²": "2", "³": "3",
}

# (source-filename-in-assets, expected height, output-module-filename)
# Bitmapped fonts (.pcf/.bdf) carry their own size; the height here is an
# assertion against the embedded value, not an input.
FONTS = [
    ("unscii_8.pcf",   8,  "unscii_8.py"),
    ("unscii_16.pcf", 16,  "unscii_16.py"),
    ("spleen-5x8.bdf", 8,  "spleen_5x8.py"),
]

MODULE_TEMPLATE = '''\
"""Generated by tools/compile_fonts.py from {src_name} — do not edit.

{height}px glyph table, ASCII + Latin-1 codepoints 32..255, framebuf.MONO_HLSB
packed (rows byte-padded, MSB = leftmost pixel). `GLYPHS[codepoint - 32]` is a
ready-to-blit `(memoryview, width, HEIGHT, framebuf.MONO_HLSB)` tuple;
`DEFAULT` is the fallback glyph ('?') for out-of-range codepoints, and table
entries the source font has no glyph for (the C1 control gap, any coverage
holes) resolve to the shared DEFAULT tuple. The table is built once at import
(on Core 0), so rendering via scoreboard.fonts.FontWriter never allocates on
the display thread.
"""
import framebuf

HEIGHT = {height}

# Per-glyph records: u16-LE width prefix + bitmap rows. Entry offsets live in
# _index (u16-LE each): [0] = default glyph, [1..{char_count}] = chars
# {minchar}..{maxchar}; absent glyphs carry 0xFFFF and share DEFAULT.
{font_literal}

{index_literal}

_mv = memoryview(_font)

# Entries that share a record (absent -> DEFAULT, blank placeholders -> their
# ASCII stand-in) share ONE tuple: the dedup dict is import-scoped scaffolding
# and is deleted (GC'd) once the table is built.
_by_off = {{}}


def _entry(i):
    o = _index[2 * i] | (_index[2 * i + 1] << 8)
    if o == 0xFFFF:
        return None
    if o not in _by_off:
        w = _font[o] | (_font[o + 1] << 8)
        _by_off[o] = (_mv[o + 2:o + 2 + ((w - 1) // 8 + 1) * HEIGHT], w,
                      HEIGHT, framebuf.MONO_HLSB)
    return _by_off[o]


DEFAULT = _entry(0)
GLYPHS = tuple(_entry(i) or DEFAULT for i in range(1, {char_count} + 1))
del _entry, _by_off
'''


def bytes_literal(name: str, blob: bytes, per_line: int = 16) -> str:
    """Emit `name = (b'...' b'...')` with fixed-width hex escapes."""
    lines = [f"{name} = ("]
    for i in range(0, len(blob), per_line):
        chunk = blob[i:i + per_line]
        lines.append("    b'" + "".join(f"\\x{b:02x}" for b in chunk) + "'")
    lines.append(")")
    return "\n".join(lines)


def build_blobs(src: Path, expected_height: int) -> tuple[bytes, bytes, int]:
    """Render one font via font_to_py; returns (_font, _index, glyph_count).

    Builds the record/index blobs directly from font_to_py's `Font` dict
    rather than `build_arrays()` — its dense-index path is hardwired to the
    95-char ASCII range and silently switches to a sparse format beyond it.
    The record layout is identical to what build_arrays emits (u16-LE width
    prefix + MONO_HLSB rows); absent codepoints get the ABSENT index sentinel.
    """
    # Bitmapped fonts define their own pixel size; mirror font_to_py's CLI,
    # which ignores the height argument and reads the embedded size.
    face = freetype.Face(str(src))
    size = face._get_available_sizes()[0].height

    # Only codepoints the font actually covers are rendered; the rest fall
    # back to DEFAULT at import. DEFCHAR coverage is non-negotiable.
    avail = {
        cp for cp in range(MINCHAR, MAXCHAR + 1)
        if cp not in _CONTROL_GAP and face.get_char_index(chr(cp)) != 0
    }
    if DEFCHAR not in avail:
        raise SystemExit(f"{src.name}: font has no glyph for the default char '?'")

    fnt = font_to_py.Font(
        str(src), size, MINCHAR, MAXCHAR,
        monospaced=False, defchar=DEFCHAR,
        charset="".join(map(chr, sorted(avail))), bitmapped=True,
    )
    if fnt.height != expected_height:
        raise SystemExit(
            f"{src.name}: rendered height {fnt.height} != expected {expected_height}"
        )

    data = bytearray()
    offsets: dict[str, int] = {}

    def record(char: str) -> int:
        if char not in offsets:
            offsets[char] = len(data)
            data.extend(fnt[char][1].to_bytes(2, "little"))
            data.extend(fnt.stream_char(char, hmap=True, reverse=False))
        return offsets[char]

    def is_blank(char: str) -> bool:
        return not any(fnt.stream_char(char, hmap=True, reverse=False))

    drawn = 0
    stood_in = 0
    index = bytearray()
    index += record(chr(DEFCHAR)).to_bytes(2, "little")  # entry 0: default
    for cp in range(MINCHAR, MAXCHAR + 1):
        char = chr(cp)
        if cp not in avail:
            off = ABSENT
        elif cp not in _ALLOWED_BLANK and is_blank(char):
            # Placeholder bitmap: reuse the ASCII stand-in's record, or fall
            # back to the default glyph when there is no sensible stand-in.
            sub = _BLANK_STAND_IN.get(char)
            if sub is None:
                off = ABSENT
            else:
                if is_blank(sub):
                    raise SystemExit(
                        f"{src.name}: stand-in {sub!r} for {char!r} is blank"
                    )
                off = record(sub)
                stood_in += 1
        else:
            off = record(char)
            drawn += 1
        index += off.to_bytes(2, "little")

    if len(data) >= ABSENT:
        raise SystemExit(f"{src.name}: font blob too large for u16 offsets")
    return bytes(data), bytes(index), (drawn, stood_in)


def compile_all() -> None:
    if not ASSETS_DIR.is_dir():
        raise SystemExit(f"Error: assets directory not found: {ASSETS_DIR}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for src_name, height, out_name in FONTS:
        src = ASSETS_DIR / src_name
        if not src.is_file():
            raise SystemExit(f"Error: missing font source {src}")

        font_blob, index_blob, (drawn, stood_in) = build_blobs(src, height)
        module = MODULE_TEMPLATE.format(
            src_name=src_name,
            height=height,
            char_count=CHAR_COUNT,
            minchar=MINCHAR,
            maxchar=MAXCHAR,
            font_literal=bytes_literal("_font", font_blob),
            index_literal=bytes_literal("_index", index_blob),
        )
        out = OUTPUT_DIR / out_name
        out.write_text(module, encoding="utf-8", newline="\n")
        print(f"[{out_name}] {src_name}: {len(font_blob)} B data, "
              f"{drawn} drawn + {stood_in} stand-in glyphs over "
              f"{CHAR_COUNT + 1} entries, height {height}")

    print(f"\nDone: {len(FONTS)} font(s) written to "
          f"{OUTPUT_DIR.relative_to(REPO_ROOT).as_posix()}/")


def main():
    compile_all()


if __name__ == "__main__":
    main()
