#!/usr/bin/env python3
"""
Generate a WiFi QR code as RGB565 bytearray for the Pico display.

TEMPORARY - This is prototype code for testing QR code display.

Usage:
    python tools/generate_wifi_qr.py

Output:
    Generates firmware/src/lib/scoreboard/qr_data.py with the QR code data.
"""

import qrcode
from pathlib import Path


def generate_wifi_qr(ssid: str, password: str = "", security: str = "nopass") -> bytes:
    """
    Generate a WiFi QR code and return as RGB565 bytes.

    Args:
        ssid: Network name
        password: Network password (empty for open networks)
        security: "WPA", "WEP", or "nopass"

    Returns:
        RGB565 bytes (little-endian, 2 bytes per pixel)
    """
    # WiFi QR code format
    if security == "nopass":
        wifi_string = f"WIFI:T:nopass;S:{ssid};;"
    else:
        wifi_string = f"WIFI:T:{security};S:{ssid};P:{password};;"

    print(f"Generating QR code for: {wifi_string}")

    # Generate QR code
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=2,  # 2 pixels per module
        border=1,    # 1 module border (will be 2 pixels)
    )
    qr.add_data(wifi_string)
    qr.make(fit=True)

    # Get the QR matrix
    matrix = qr.get_matrix()
    height = len(matrix)
    width = len(matrix[0]) if matrix else 0

    print(f"QR code size: {width}x{height} pixels")

    # Convert to RGB565
    # White = 0xFFFF, Black = 0x0000
    WHITE = 0xFFFF
    BLACK = 0x0000

    rgb565_bytes = bytearray()
    for row in matrix:
        for cell in row:
            color = BLACK if cell else WHITE
            # Little-endian format
            rgb565_bytes.append(color & 0xFF)
            rgb565_bytes.append((color >> 8) & 0xFF)

    return bytes(rgb565_bytes), width, height


def main():
    # Generate QR code for default SSID "scoreboard"
    ssid = "scoreboard"
    qr_bytes, width, height = generate_wifi_qr(ssid)

    print(f"Generated {len(qr_bytes)} bytes ({width}x{height} pixels)")

    # Format as Python bytearray
    output_path = Path(__file__).parent.parent / "firmware" / "src" / "lib" / "scoreboard" / "qr_data.py"

    # Create hex string representation
    hex_lines = []
    bytes_per_line = 16
    for i in range(0, len(qr_bytes), bytes_per_line):
        chunk = qr_bytes[i:i + bytes_per_line]
        hex_str = " ".join(f"0x{b:02x}," for b in chunk)
        hex_lines.append(f"    {hex_str}")

    hex_content = "\n".join(hex_lines)

    output_content = f'''"""
TEMPORARY - WiFi QR Code Data for Setup Screen.

This file is auto-generated by tools/generate_wifi_qr.py
REMOVE THIS FILE when QR code feature is no longer needed.

QR Code Info:
- SSID: {ssid}
- Security: Open (no password)
- Size: {width}x{height} pixels
- Format: RGB565 little-endian
"""

# ============================================================
# TEMPORARY CODE - REMOVE LATER
# ============================================================

import framebuf

# QR code dimensions
QR_WIDTH = {width}
QR_HEIGHT = {height}

# RGB565 pixel data (little-endian)
_QR_DATA = bytearray([
{hex_content}
])

def get_qr_framebuffer():
    """Get the WiFi QR code as a framebuffer for blitting."""
    return framebuf.FrameBuffer(_QR_DATA, QR_WIDTH, QR_HEIGHT, framebuf.RGB565)

# ============================================================
# END TEMPORARY CODE
# ============================================================
'''

    output_path.write_text(output_content)
    print(f"Written to: {output_path}")


if __name__ == "__main__":
    main()
